### ISSUE TITLE
ElasticSinkConnector: Task 0 is FAILED (NoNodeAvailableException)

### ISSUE THREAD

**Issue by costa** [Landoop/stream-reactor#229]
Please see https://github.com/datamountaineer/stream-reactor/issues/177#issuecomment-312865600 for details, I don't seem to be able to use the connector with ES5 still (the Confluent's connector works well, this connector works well with ES2).

**Comment by andrewstevenson** [comment]
@costa I'n #177 the stack trace indicates you are still using the `elastic` connector rather than `elastic5`, it's a different class so the class name in the connector properties should reflect this.

**Comment by stheppi** [comment]
@costa,
  We provide two ES sink, one for 2.x and one for 5.x.  we differentiate it will allow sink for 2.0 run sife by side of a sink for 5.0.

Now, back to the error. You seem to have a connection issue there. A quick google search got me here: https://stackoverflow.com/questions/33691858/elasticsearch-nonodeavailableexception . Please check your cluster is accessible given your infrastructure.

**Comment by costa** [comment]
@stheppi Re: namespacing/versioning: I understand the intention, but not the purpose, I just fail to see an architecture where two ES clusters of different versions need to be accessible from the same JVM.

Nevermind that.

Your quick google search got you a vaguely relevant ES2 Q&A. My multiple and extensive google searches didn't help me to solve this problem. As mentioned above, I do test my ES5 to open 9300 long before I try to create the sink. Also mentioned above, the Confluent's sink drop-in replacement **works** (with 9200). Can you kindly share your ES5 testing setup please?

**Comment by andrewstevenson** [comment]
@costa There are two namespaces because 1) version dependencies issues 2) clients do write to more than one elastic cluster on different versions in the same connector cluster. For example to migrating from 2x to 5x.

Here's our integration test http://coyote.landoop.com/connect/kafka-connect-elastic5/

Are you running in a docker? What's you connector configuration? Have you set the elastic clustername?

In our experince and that of the author of the underlying elastic4s library we use, is that the clustername is not set or different from the default or that the cluster is not accessible.
https://stackoverflow.com/questions/45577077/elastic4s-nonodeavailableexception-when-connecting-through-tcpclient-transport

**Comment by costa** [comment]
@andrewstevenson @stheppi I'm currently trying to solve this problem, please note, the other connector works in the very same environment — I literally have a `case` to switch the sink classes+configs.

Meanwhile, a less related question: how did you manage to have environment variables in your docker-compose.yml (to configure elasticsearch) with dots in them? It doesn't work with my docker-compose and I have to resort to the command-line options.

Will post any progress here, appreciate if you re-open the issue.

**Comment by andrewstevenson** [comment]
Which docker compose? we haven't published any docker compose files.

**Comment by costa** [comment]
https://github.com/Landoop/kafka-connectors-tests/blob/master/kafka-connect-elastic5/docker-compose.yml
I thought you were testing with this.

**Comment by Antwnis** [comment]
Please share your docker-compose version

    `$docker-compose -version`

Also please share the `configuration` you are posting to the Connector

Also try the same config using `landoop/fast-data-dev:cp3.3.0` docker image and let us know if it works there

**Comment by costa** [comment]
@Antwnis Thanks for the docker-compose tip, 1.7 works.

Used the image you mentioned, same result:
```
[2017-11-07 14:09:33,651] INFO ElasticConfig values: 
	connect.elastic.batch.size = 4000
	connect.elastic.cluster.name = elasticsearch
	connect.elastic.error.policy = THROW
	connect.elastic.kcql = INSERT INTO vital SELECT * FROM Vital
	connect.elastic.max.retries = 20
	connect.elastic.url = elasticsearch:9300
	connect.elastic.url.prefix = elasticsearch
	connect.elastic.use.http = tcp
	connect.elastic.write.timeout = 300000
	connect.elastic.xpack.plugins = null
	connect.elastic.xpack.settings = null
	connect.progress.enabled = false
 (com.datamountaineer.streamreactor.connect.elastic5.config.ElasticConfig:223)
[2017-11-07 14:09:33,653] INFO Kafka version : 0.11.0.0-cp1 (org.apache.kafka.common.utils.AppInfoParser:83)
[2017-11-07 14:09:33,654] INFO Kafka commitId : 5cadaa94d0a69e0d (org.apache.kafka.common.utils.AppInfoParser:84)
[2017-11-07 14:09:33,655] INFO Finished starting connectors and tasks (org.apache.kafka.connect.runtime.distributed.DistributedHerder:825)
[2017-11-07 14:09:33,656] INFO Source task WorkerSourceTask{id=logs-broker-0} finished initialization and start (org.apache.kafka.connect.runtime.WorkerSourceTask:143)
[2017-11-07 14:09:33,687] INFO Initialising Elastic Json writer (com.datamountaineer.streamreactor.connect.elastic5.ElasticJsonWriter:45)
[2017-11-07 14:09:33,687] INFO Sink task WorkerSinkTask{id=Vital-ElasticSinkConnector-0} finished initialization and start (org.apache.kafka.connect.runtime.WorkerSinkTask:233)
[2017-11-07 14:09:33,690] INFO Discovered coordinator 1fe90d48e1db:9092 (id: 2147483647 rack: null) for group connect-Vital-ElasticSinkConnector. (org.apache.kafka.clients.consumer.internals.AbstractCoordinator:597)
[2017-11-07 14:09:33,691] INFO Revoking previously assigned partitions [] for group connect-Vital-ElasticSinkConnector (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:419)
[2017-11-07 14:09:33,691] INFO (Re-)joining group connect-Vital-ElasticSinkConnector (org.apache.kafka.clients.consumer.internals.AbstractCoordinator:432)
[2017-11-07 14:09:33,694] INFO Successfully joined group connect-Vital-ElasticSinkConnector with generation 3 (org.apache.kafka.clients.consumer.internals.AbstractCoordinator:399)
[2017-11-07 14:09:33,694] INFO Setting newly assigned partitions [Vital-0] for group connect-Vital-ElasticSinkConnector (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:262)
[2017-11-07 14:09:33,713] ERROR Encountered error None of the configured nodes are available: [{#transport#-1}{Ww1x0MHNSoeiEHBUV7tynw}{elasticsearch}{172.19.0.2:9300}] (com.datamountaineer.streamreactor.connect.elastic5.ElasticJsonWriter:62)
NoNodeAvailableException[None of the configured nodes are available: [{#transport#-1}{Ww1x0MHNSoeiEHBUV7tynw}{elasticsearch}{172.19.0.2:9300}]]
	at org.elasticsearch.client.transport.TransportClientNodesService.ensureNodesAreAvailable(TransportClientNodesService.java:348)
	at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:246)
	at org.elasticsearch.client.transport.TransportProxyClient.execute(TransportProxyClient.java:59)
	at org.elasticsearch.client.transport.TransportClient.doExecute(TransportClient.java:366)
	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:408)
	at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:80)
	at com.sksamuel.elastic4s.bulk.BulkExecutables$BulkDefinitionExecutable$$anonfun$apply$4.apply(BulkExecutables.scala:28)
	at com.sksamuel.elastic4s.bulk.BulkExecutables$BulkDefinitionExecutable$$anonfun$apply$4.apply(BulkExecutables.scala:28)
	at com.sksamuel.elastic4s.Executable$class.injectFutureAndMap(Executable.scala:21)
	at com.sksamuel.elastic4s.bulk.BulkExecutables$BulkDefinitionExecutable$.injectFutureAndMap(BulkExecutables.scala:17)
	at com.sksamuel.elastic4s.bulk.BulkExecutables$BulkDefinitionExecutable$.apply(BulkExecutables.scala:28)
	at com.sksamuel.elastic4s.bulk.BulkExecutables$BulkDefinitionExecutable$.apply(BulkExecutables.scala:17)
	at com.sksamuel.elastic4s.TcpClient$class.execute(TcpClient.scala:28)
	at com.sksamuel.elastic4s.TcpClientConstructors$$anon$1.execute(TcpClient.scala:46)
	at com.datamountaineer.streamreactor.connect.elastic5.TcpKElasticClient.execute(KElasticClient.scala:69)
	at com.datamountaineer.streamreactor.connect.elastic5.ElasticJsonWriter$$anonfun$10$$anonfun$apply$4$$anonfun$apply$5.apply(ElasticJsonWriter.scala:146)
	at com.datamountaineer.streamreactor.connect.elastic5.ElasticJsonWriter$$anonfun$10$$anonfun$apply$4$$anonfun$apply$5.apply(ElasticJsonWriter.scala:116)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:410)
...
```

**Comment by stheppi** [comment]
@costa 
  can you please change the code in  ElasticWriter.scala line 39:

```val uri: ElasticsearchClientUri = ElasticsearchClientUri(s"$esPrefix://$hostNames?cluster.name=$esClusterName")```

 Then build and deploy the jar and let us know the outcome.

**Comment by andrewstevenson** [comment]
@costa Also I've just spun a 5x cluster up on elastic cloud, I have no problems connecting

by Andrew Stevenson v  (com.datamountaineer.streamreactor.connect.elastic5.ElasticSinkTask:39)
[2017-11-07 17:02:00,683] INFO ElasticConfig values:
	connect.elastic.batch.size = 4000
	connect.elastic.cluster.name = elasticsearch
	connect.elastic.error.policy = THROW
	connect.elastic.kcql = INSERT INTO index_1 SELECT * FROM orders-topic
	connect.elastic.max.retries = 20
	connect.elastic.url = 177eb7db0aeafc9229b5ee4ec9458be1.eu-west-1.aws.found.io:9343
	connect.elastic.url.prefix = elasticsearch
	connect.elastic.use.http = tcp
	connect.elastic.write.timeout = 300000
	connect.elastic.xpack.plugins = null
	connect.elastic.xpack.settings = [hidden]
	connect.progress.enabled = true
 (com.datamountaineer.streamreactor.connect.elastic5.config.ElasticConfig:223)
[2017-11-07 17:02:02,555] INFO Initialising Elastic Json writer (com.datamountaineer.streamreactor.connect.elastic5.ElasticJsonWriter:45)
[2017-11-07 17:02:02,561] INFO Sink task WorkerSinkTask{id=es4-0} finished initialization and start (org.apache.kafka.connect.runtime.WorkerSinkTask:233)
[2017-11-07 17:02:02,666] WARN Error while fetching metadata with correlation id 2 : {orders-topic=LEADER_NOT_AVAILABLE} (org.apache.kafka.clients.NetworkClient:846)
[2017-11-07 17:02:02,667] INFO Discovered coordinator 192.168.178.52:9092 (id: 2147483647 rack: null) for group connect-es4. (org.apache.kafka.clients.consumer.internals.AbstractCoordinator:597)
[2017-11-07 17:02:02,668] INFO Revoking previously assigned partitions [] for group connect-es4 (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:419)
[2017-11-07 17:02:02,668] INFO (Re-)joining group connect-es4 (org.apache.kafka.clients.consumer.internals.AbstractCoordinator:432)
[2017-11-07 17:02:02,777] INFO Successfully joined group connect-es4 with generation 1 (org.apache.kafka.clients.consumer.internals.AbstractCoordinator:399)
[2017-11-07 17:02:02,778] INFO Setting newly assigned partitions [orders-topic-0] for group connect-es4 (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:262)

**Comment by costa** [comment]
@stheppi Hi, sorry for the delay, I don't actually have this project's development environment. I've just been using the docker image, I'm sorry. So either you direct me to a simple and concise dev env init procedure (so I can build such a docker image myself), or you will be so kind as to prepare the docker image yourself. Thanks!

@andrewstevenson Ye, good ol' "works for me", thanks a lot ;)  Now really, the whole idea of containerisation is to eliminate this gap. So kindly provide a `docker-compose.yml` or tell me how you test your `fast-data-dev` docker image please.
Again, I was under impression that was it: https://github.com/Landoop/kafka-connectors-tests/blob/master/kafka-connect-elastic5/docker-compose.yml

**Comment by andrewstevenson** [comment]
@costa That's a test docker compose we use for testing.

If you are unable to get your docker working, try without first. Our fast data dev has no issues as do other clients.

Feel submit any PRs, contributions are more than welcome

**Comment by Antwnis** [comment]
Hi @costa we discussed to blog about **coyote** a little bit

It's such a brilliant tool and can help you try out setups + connectors internally

So we'll generate an easy to follow tutorial in the near future under https://landoop.com/blog/

**Comment by Antwnis** [comment]
additionally in the open source community: things like `help me if you have time` work better to `direct me to a simple and concise answer` ;-) Tickets are expecting someone in the community to address them via a PR and contributions are always welcome

**Comment by andrewstevenson** [comment]
@costa Any issue here is with your docker or elastic setup. Not the connector. Docker experts are free to provide PRs. Hence closed. I'd love to be proved wrong and see a PR raised.

**Comment by andmarios** [comment]
To me it seems that the connector cannot connect to ElasticSearch.
The first steps to debug would be to connect to the machine/VM/container that runs the connector and check ElasticSearch connectivity.

So if for example you run the connector inside a container named `costa`, I would do:

    docker exec -it costa bash

Once inside, I would check if ElasticSearch is available and configured as expected. For example by curl'ing the ES HTTP port, I can check that both _cluster.name_ and _elastic version_ are correct. Also I check that the IP or domain I use for ES is correct and accessible as well:
```
$ curl elasticsearch:9200
{
  "name" : "LwX60Ec",
  "cluster_name" : "landoop",
  "cluster_uuid" : "-tD8fLlrQRGJLgRpVMPINw",
  "version" : {
    "number" : "5.4.0",
    "build_hash" : "780f8c4",
    "build_date" : "2017-04-28T17:43:27.229Z",
    "build_snapshot" : false,
    "lucene_version" : "6.5.0"
  },
  "tagline" : "You Know, for Search"
}
```

Then I would check if the native port of ElasticSearch is available to the container running the connector:

```
$ curl elasticsearch:9300
This is not a HTTP port
```

I hope this helps a bit.

**Comment by costa** [comment]
Ok, thanks all for your help, the @andmarios' hint directed me to find the culprit: the official ES docker image has its cluster.name different from the default for some reason, and the http-port connector doesn't have that option to screw things up. Thank you again and the issue is now truly closed.

**Comment by andmarios** [comment]
We chose to go native for better performance. Alas it is a bit more difficult to configure and we need to have two different connectors as they need to load different versions of elastic's classes.

Glad we reached to the bottom of this!
