### ISSUE TITLE
Error while passing composite primary key

### ISSUE THREAD

**Issue by himani1** [Landoop/stream-reactor#318]
I am trying to deploy a Cassandra source connector with the following properties:

{
	"name": "test-source-connector",
	"config": {
		"connector.class": "com.datamountaineer.streamreactor.connect.cassandra.source.CassandraSourceConnector",
		"connect.cassandra.key.space": "testdb",
		"connect.cassandra.contact.points": "xxx.xx.xx",
		"tasks.max": "5",
		"connect.cassandra.port": "9042",
		"connect.cassandra.kcql": "INSERT INTO test-topic SELECT * FROM test-table PK date,last_updated INCREMENTALMODE=TIMESTAMP",
		"name": "test-source-connector",
		"connect.cassandra.password": "cassandra",
		"connect.cassandra.import.poll.interval": "5000",
		"connect.cassandra.username": "cassandra"
	}
}

I am getting the following error when I do so,

[2017-11-16 11:33:31,818] ERROR Task test-source-connector-0 threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask)
com.datastax.driver.core.exceptions.CodecNotFoundException: Codec not found for requested operation: [varchar <-> java.util.Date]
    at com.datastax.driver.core.CodecRegistry.notFound(CodecRegistry.java:679)
    at com.datastax.driver.core.CodecRegistry.createCodec(CodecRegistry.java:540)
    at com.datastax.driver.core.CodecRegistry.findCodec(CodecRegistry.java:520)
    at com.datastax.driver.core.CodecRegistry.codecFor(CodecRegistry.java:470)
    at com.datastax.driver.core.AbstractGettableByIndexData.codecFor(AbstractGettableByIndexData.java:77)
    at com.datastax.driver.core.BoundStatement.bind(BoundStatement.java:196)
    at com.datastax.driver.core.DefaultPreparedStatement.bind(DefaultPreparedStatement.java:126)
    at com.datamountaineer.streamreactor.connect.cassandra.source.CassandraTableReader.bindAndFireTimebasedQuery(CassandraTableReader.scala:149)
    at com.datamountaineer.streamreactor.connect.cassandra.source.CassandraTableReader.query(CassandraTableReader.scala:128)
    at com.datamountaineer.streamreactor.connect.cassandra.source.CassandraTableReader.read(CassandraTableReader.scala:108)
    at com.datamountaineer.streamreactor.connect.cassandra.source.CassandraSourceTask.process(CassandraSourceTask.scala:131)
    at com.datamountaineer.streamreactor.connect.cassandra.source.CassandraSourceTask$$anonfun$poll$2.apply(CassandraSourceTask.scala:108)
    at com.datamountaineer.streamreactor.connect.cassandra.source.CassandraSourceTask$$anonfun$poll$2.apply(CassandraSourceTask.scala:108)
    at scala.collection.generic.GenericTraversableTemplate$$anonfun$flatten$1.apply(GenericTraversableTemplate.scala:172)
    at scala.collection.generic.GenericTraversableTemplate$$anonfun$flatten$1.apply(GenericTraversableTemplate.scala:171)
    at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
    at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
    at scala.collection.generic.GenericTraversableTemplate$class.flatten(GenericTraversableTemplate.scala:171)
    at scala.collection.AbstractTraversable.flatten(Traversable.scala:104)
    at com.datamountaineer.streamreactor.connect.cassandra.source.CassandraSourceTask.poll(CassandraSourceTask.scala:108)
    at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:162)
    at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:139)
    at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:182)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

**Comment by andrewstevenson** [comment]
@himani1 What is the schema of your table in Cassandra?

**Comment by CodeSmell** [comment]
The `CassandraSource` only expects one column as the PK from which it will manage the time ranges that it will query Cassandra for data. 

So the following: 
`INSERT INTO test-topic SELECT * FROM test-table PK date,last_updated INCREMENTALMODE=TIMESTAMP",`

should probably be more like:
`INSERT INTO test-topic SELECT * FROM test-table PK last_updated INCREMENTALMODE=TIMESTAMP",`

assuming `last_updated` is the column representing when the rest of the data changed

**Comment by ramindukuri** [comment]
Thanks so much andrew and Codesmell.

Question 1: 
Table's schema above has PRIMARY KEY (date,last_updated)  where date is date and last_updated is timestamp. This is done to avoid full table scans hoping to generate some thing like 

SELECT * FROM test-table WHERE date = '2017-11-16' and  last_updated > ? AND last_updated <= ? ALLOW FILTERING

is this possible to generate with kcql ?

Question 2:  If above is not possible.
Lets say we design  table as  PRIMARY KEY ( colA, colB) and if we say 
"connect.cassandra.kcql": "INSERT INTO test-topic SELECT * FROM test-table PK last_updated INCREMENTALMODE=TIMESTAMP",  it works with ALLOW_FILTERING. However, we suspect this fails when the size of table is large. 

In this case, what is the best way to pull data incremental ?

**Comment by CodeSmell** [comment]
@ramindukuri 
> Question 1: is this possible to generate with kcql ?
No

> Question 2: what is the best way to pull data incremental ?
You are correct that under large sets of data there can be issues. 
Issue #278 has addressed much of this by allowing users to configure the size of the time slice and thus control the amount of data that is retrieved at any point in time.
