### ISSUE TITLE
Kafka connect HBase: java.lang.NoClassDefFoundError: Could not initialize class org.apache.hadoop.hbase.util.ByteStringer

### ISSUE THREAD

**Issue by artiship** [Landoop/stream-reactor#321]
0. confluent verion is  3.3.0 
stream-reactor-0.3.0-3.3.0.tar.gz
remote hbase version is cdh-5.8.0

1. Add hbase-site.xml to solve remote hbase connecting issue https://github.com/Landoop/stream-reactor/issues/96#issuecomment-345184072
```bash
jar -uvf kafka-connect-hbase-0.3.0-3.3.0-all.jar hbase-site.xml
```
2. Restart confluent connect
```bash 
bin/confluent stop conenct
bin/confluent start connect
```
3. Start connector task example [http://docs.datamountaineer.com/en/latest/hbase.html](http://docs.datamountaineer.com/en/latest/hbase.html)
```bash
➜  bin/connect-cli create hbase-sink < conf/hbase-sink.properties
#Connector name=`hbase-sink`
name=person-hbase-test
connector.class=com.datamountaineer.streamreactor.connect.hbase.HbaseSinkConnector
tasks.max=1
topics=hbase-topic
connect.hbase.column.family=d
connect.hbase.kcql=INSERT INTO person SELECT * FROM hbase-topic PK firstName, lastName
#task ids: 0
```

4. Error log:

```log
...skipping...
        at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:251)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:180)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:148)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:146)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:190)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
[2017-11-17 17:12:10,949] ERROR Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerSinkTask:456)
[2017-11-17 17:12:10,949] ERROR Task hbase-sink-test-0 threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask:148)
org.apache.kafka.connect.errors.ConnectException: Exiting WorkerSinkTask due to unrecoverable exception.
        at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:457)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:251)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:180)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:148)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:146)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:190)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
[2017-11-17 17:12:10,950] ERROR Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask:149)
[2017-11-17 17:12:10,950] INFO Stopping Hbase sink. (com.datamountaineer.streamreactor.connect.hbase.HbaseSinkTask:95)
[2017-11-17 17:12:10,956] ERROR Task hbase-sink-test-0 threw an uncaught and unrecoverable exception during shutdown (org.apache.kafka.connect.runtime.WorkerTask:127)
java.lang.NoClassDefFoundError: Could not initialize class org.apache.hadoop.hbase.util.ByteStringer
        at org.apache.hadoop.hbase.protobuf.RequestConverter.buildRegionSpecifier(RequestConverter.java:1037)
        at org.apache.hadoop.hbase.protobuf.RequestConverter.buildGetRowOrBeforeRequest(RequestConverter.java:142)
        at org.apache.hadoop.hbase.protobuf.ProtobufUtil.getRowOrBefore(ProtobufUtil.java:1590)
        at org.apache.hadoop.hbase.client.ConnectionManager$HConnectionImplementation.locateRegionInMeta(ConnectionManager.java:1398)
        at org.apache.hadoop.hbase.client.ConnectionManager$HConnectionImplementation.locateRegion(ConnectionManager.java:1199)
        at org.apache.hadoop.hbase.client.AsyncProcess.submit(AsyncProcess.java:410)
        at org.apache.hadoop.hbase.client.AsyncProcess.submit(AsyncProcess.java:359)
        at org.apache.hadoop.hbase.client.BufferedMutatorImpl.backgroundFlushCommits(BufferedMutatorImpl.java:238)
        at org.apache.hadoop.hbase.client.BufferedMutatorImpl.flush(BufferedMutatorImpl.java:190)
        at org.apache.hadoop.hbase.client.HTable.flushCommits(HTable.java:1498)
        at org.apache.hadoop.hbase.client.HTable.close(HTable.java:1534)
        at com.datamountaineer.streamreactor.connect.hbase.writers.HbaseWriter$$anonfun$close$1.apply(HbaseWriter.scala:111)
        at com.datamountaineer.streamreactor.connect.hbase.writers.HbaseWriter$$anonfun$close$1.apply(HbaseWriter.scala:111)
        at scala.collection.immutable.Map$Map1.foreach(Map.scala:116)
        at com.datamountaineer.streamreactor.connect.hbase.writers.HbaseWriter.close(HbaseWriter.scala:111)
        at com.datamountaineer.streamreactor.connect.hbase.HbaseSinkTask$$anonfun$stop$1.apply(HbaseSinkTask.scala:96)
        at com.datamountaineer.streamreactor.connect.hbase.HbaseSinkTask$$anonfun$stop$1.apply(HbaseSinkTask.scala:96)
        at scala.Option.foreach(Option.scala:257)
        at com.datamountaineer.streamreactor.connect.hbase.HbaseSinkTask.stop(HbaseSinkTask.scala:96)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.close(WorkerSinkTask.java:131)
        at org.apache.kafka.connect.runtime.WorkerTask.doClose(WorkerTask.java:125)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:152)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:190)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
...skipping...
        at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:251)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:180)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:148)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:146)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:190)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
[2017-11-17 17:12:10,949] ERROR Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerSinkTask:456)
```

**Comment by AirTobe91** [comment]
If I get it right, it sounds like, that connect don't know your kafka-connect-hbase.jar.
When you're calling "confluent start" it is taking the config from $CONFLUENT_HOME/etc/schema-registry/connect-avro-distributed.properties. At the end of this file, there is a plugin.path variable. This has to contain the $STREAMREACTOR_HOME/libs folder, or just generate a folder and copy your kafka-connect-hbaseXXX.jar in this folder. 

E.g.
> mkdir ~/kafkaConnectors
> cp $STREAMREACTOR_HOME/libs/kafka-connect-hbase.jar ~/kafkaConnectors
> vi $CONFLUENT_HOME/etc/schema-registry/connect-avro-distributed.properties
> plugin.path=/home/*youruser*/kafkaConnectors (I had to write /home/*youruser* because it hasn't inpreted ~ correctly)
> confluent stop
> confluent start

If your now using "confluent log connect", there should be something stated about your hbase connector.
Example for my Cassandra Connector:
[2017-11-17 11:13:19,819] INFO Added plugin 'com.datamountaineer.streamreactor.connect.cassandra.sink.CassandraSinkConnector' (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:132)
[2017-11-17 11:13:19,819] INFO Added plugin 'com.datamountaineer.streamreactor.connect.cassandra.source.CassandraSourceConnector' (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:132)

Now try again "bin/connect-cli create hbase-sink < conf/hbase-sink.properties" and it should know you kafka-connect-hbase class.

**Comment by artiship** [comment]
@AirTobe91 Thanks for your comment. I had configured plugin.path and the log indeed state about adding hbase connector class information. And it connects to hbase successfully, but it throws out could not  initialize class org.apache.hadoop.hbase.util.ByteStringer exception during the process in RequestConverter in hbase-client.jar, and the ByteStringer class is in hbase-protobuf. jar. My hbase version  is cdh-5.8.0. Then I try to modify hbase version in source gradle file and rebuild the kafka-connector-hbase jar. The above exception was not appeared, but another exception throws and the kafka topic data were not sinked to hbase.

**Comment by stheppi** [comment]
@artiship ,
  It does not matter if you use a higher version of HBase server. 
  What is the error you see after your build?

**Comment by artiship** [comment]
@stheppi,
1. gradle.build
```groovy
project(":kafka-connect-hbase") {

    ext {
        hbaseClientVersion = "1.2.0-cdh5.12.0"
        guavaVersion = "12.0.1"
        hdfsVersion="2.6.0-cdh5.12.0"
    }

    dependencies {
        compile("com.google.guava:guava:$guavaVersion") {
            force = true
        }

        compile "org.apache.hadoop:hadoop-hdfs:$hdfsVersion"

        compile("org.apache.hbase:hbase-client:$hbaseClientVersion") {
            exclude group: "tomcat"
        }

        testCompile group: 'org.kitesdk', name: 'kite-minicluster', version: '1.0.0-cdh5.12.0'
        testCompile("org.json4s:json4s-native_$scalaMajorVersion:$json4sVersion")
    }
}
```
2. Showing all added plugins:
```bash
bin/connect-cli plugins
Class name: ConnectorPlugins(com.datamountaineer.streamreactor.connect.azure.documentdb.sink.DocumentDbSinkConnector)
Class name: ConnectorPlugins(com.datamountaineer.streamreactor.connect.blockchain.source.BlockchainSourceConnector)
Class name: ConnectorPlugins(com.datamountaineer.streamreactor.connect.bloomberg.BloombergSourceConnector)
Class name: ConnectorPlugins(com.datamountaineer.streamreactor.connect.cassandra.sink.CassandraSinkConnector)
Class name: ConnectorPlugins(com.datamountaineer.streamreactor.connect.cassandra.source.CassandraSourceConnector)
Class name: ConnectorPlugins(com.datamountaineer.streamreactor.connect.coap.sink.CoapSinkConnector)
Class name: ConnectorPlugins(com.datamountaineer.streamreactor.connect.coap.source.CoapSourceConnector)
Class name: ConnectorPlugins(com.datamountaineer.streamreactor.connect.druid.DruidSinkConnector)
Class name: ConnectorPlugins(com.datamountaineer.streamreactor.connect.elastic.ElasticSinkConnector)
Class name: ConnectorPlugins(com.datamountaineer.streamreactor.connect.elastic5.ElasticSinkConnector)
Class name: ConnectorPlugins(com.datamountaineer.streamreactor.connect.ftp.source.FtpSourceConnector)
Class name: ConnectorPlugins(com.datamountaineer.streamreactor.connect.hazelcast.sink.HazelCastSinkConnector)

Class name: ConnectorPlugins(com.datamountaineer.streamreactor.connect.hbase.HbaseSinkConnector)

Class name: ConnectorPlugins(com.datamountaineer.streamreactor.connect.influx.InfluxSinkConnector)
Class name: ConnectorPlugins(com.datamountaineer.streamreactor.connect.jms.sink.JMSSinkConnector)
Class name: ConnectorPlugins(com.datamountaineer.streamreactor.connect.jms.source.JMSSourceConnector)
Class name: ConnectorPlugins(com.datamountaineer.streamreactor.connect.kudu.sink.KuduSinkConnector)
Class name: ConnectorPlugins(com.datamountaineer.streamreactor.connect.mongodb.sink.MongoSinkConnector)
Class name: ConnectorPlugins(com.datamountaineer.streamreactor.connect.mqtt.sink.MqttSinkConnector)
Class name: ConnectorPlugins(com.datamountaineer.streamreactor.connect.mqtt.source.MqttSourceConnector)
Class name: ConnectorPlugins(com.datamountaineer.streamreactor.connect.redis.sink.RedisSinkConnector)
Class name: ConnectorPlugins(com.datamountaineer.streamreactor.connect.rethink.sink.ReThinkSinkConnector)
Class name: ConnectorPlugins(com.datamountaineer.streamreactor.connect.rethink.source.ReThinkSourceConnector)
Class name: ConnectorPlugins(com.datamountaineer.streamreactor.connect.voltdb.VoltSinkConnector)
Class name: ConnectorPlugins(com.datamountaineer.streamreactor.connect.yahoo.source.YahooSourceConnector)
Class name: ConnectorPlugins(io.confluent.connect.elasticsearch.ElasticsearchSinkConnector)
Class name: ConnectorPlugins(io.confluent.connect.hdfs.HdfsSinkConnector)
Class name: ConnectorPlugins(io.confluent.connect.hdfs.tools.SchemaSourceConnector)
Class name: ConnectorPlugins(io.confluent.connect.jdbc.JdbcSinkConnector)
Class name: ConnectorPlugins(io.confluent.connect.jdbc.JdbcSourceConnector)
Class name: ConnectorPlugins(io.confluent.connect.s3.S3SinkConnector)
Class name: ConnectorPlugins(io.confluent.connect.storage.tools.SchemaSourceConnector)
Class name: ConnectorPlugins(org.apache.kafka.connect.file.FileStreamSinkConnector)
Class name: ConnectorPlugins(org.apache.kafka.connect.file.FileStreamSourceConnector)
```

3. Error log
```
StreamReactor-Version:  0.3.1-SNAPSHOT
Kafka-Version:          0.11.0.0
KCQL-Version:           2.2.0
Git-Repo:               https://github.com/Landoop/stream-reactor.git
Git-Commit-Hash:        8fb5940e3344596027843d33d95517df16cdd2a8
/_____/\\_,\\\\\\\__,_/_/  /_/\___\\\\\,\/_/ /_/\\_/\__,_/_/_/ /_/\___/\___/_/
      / / / / __ )____ _________ / ___/(_)___  / /__
     / /_/ / __  / __ `/ ___/ _ \\__ \/ / __ \/ //_/
    / __  / /_/ / /_/ (__  )  __/__/ / / / / / ,<
   /_/ /_/_____/\__,_/____/\___/____/_/_/ /_/_/|_|

By Stefan Bocutiu (com.datamountaineer.streamreactor.connect.hbase.HbaseSinkTask:49)
[2017-11-20 11:51:24,121] INFO 
StreamReactor-Version:  0.3.1-SNAPSHOT
Kafka-Version:          0.11.0.0
KCQL-Version:           2.2.0
Git-Repo:               https://github.com/Landoop/stream-reactor.git
Git-Commit-Hash:        8fb5940e3344596027843d33d95517df16cdd2a8
Git-Tag:                0.3.1-SNAPSHOT
StreamReactor-Docs:     http://docs.datamountaineer.com/en/0.3.1-SNAPSHOT/
     (com.datamountaineer.streamreactor.connect.hbase.HbaseSinkTask:50)
[2017-11-20 11:51:24,121] INFO HBaseConfig values: 
        connect.hbase.column.family = d
        connect.hbase.error.policy = THROW
        connect.hbase.kcql = INSERT INTO person SELECT * FROM hbase-topic PK firstName, lastName
        connect.hbase.max.retries = 20
        connect.hbase.retry.interval = 60000
        connect.progress.enabled = false
 (com.datamountaineer.streamreactor.connect.hbase.config.HBaseConfig:223)
[2017-11-20 11:51:24,125] INFO Settings:
HBaseSettings(d,Map(hbase-topic -> StructFieldsRowKeyBuilderBytes(List(firstName, lastName),
)),List(com.datamountaineer.kcql.Kcql@11f1a5f5),Map(hbase-topic -> StructFieldsExtractorBytes(true,Map(* -> *))),ThrowErrorPolicy(),20)
       (com.datamountaineer.streamreactor.connect.hbase.HbaseSinkTask:65)
[2017-11-20 11:51:24,130] INFO 127.0.0.1 - - [20/Nov/2017:03:51:23 +0000] "POST /connectors HTTP/1.1" 201 364  559 (org.apache.kafka.connect.runtime.rest.RestServer:60)
[2017-11-20 11:51:24,186] INFO Process identifier=hconnection-0x7b215f2f connecting to ZooKeeper ensemble=192.168.1.101:2181 (org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper:120)
[2017-11-20 11:51:24,200] INFO Sink task WorkerSinkTask{id=hbase-sink-test-0} finished initialization and start (org.apache.kafka.connect.runtime.WorkerSinkTask:233)
[2017-11-20 11:51:24,205] INFO Discovered coordinator slave2:9092 (id: 2147483647 rack: null) for group connect-hbase-sink-test. (org.apache.kafka.clients.consumer.internals.AbstractCoordinator:597)
[2017-11-20 11:51:24,206] INFO Revoking previously assigned partitions [] for group connect-hbase-sink-test (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:419)
[2017-11-20 11:51:24,207] INFO (Re-)joining group connect-hbase-sink-test (org.apache.kafka.clients.consumer.internals.AbstractCoordinator:432)
[2017-11-20 11:51:24,893] INFO Successfully joined group connect-hbase-sink-test with generation 4 (org.apache.kafka.clients.consumer.internals.AbstractCoordinator:399)
[2017-11-20 11:51:24,894] INFO Setting newly assigned partitions [hbase-topic-0] for group connect-hbase-sink-test (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:262)
[2017-11-20 11:51:24,909] ERROR Task hbase-sink-test-0 threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerSinkTask:455)
java.lang.NoClassDefFoundError: Could not initialize class org.apache.hadoop.hbase.util.ByteStringer
        at org.apache.hadoop.hbase.protobuf.RequestConverter.buildRegionSpecifier(RequestConverter.java:1037)
        at org.apache.hadoop.hbase.protobuf.RequestConverter.buildGetRowOrBeforeRequest(RequestConverter.java:142)
        at org.apache.hadoop.hbase.protobuf.ProtobufUtil.getRowOrBefore(ProtobufUtil.java:1590)
        at org.apache.hadoop.hbase.client.ConnectionManager$HConnectionImplementation.locateRegionInMeta(ConnectionManager.java:1398)
        at org.apache.hadoop.hbase.client.ConnectionManager$HConnectionImplementation.locateRegion(ConnectionManager.java:1199)
        at org.apache.hadoop.hbase.client.AsyncProcess.submit(AsyncProcess.java:410)
        at org.apache.hadoop.hbase.client.AsyncProcess.submit(AsyncProcess.java:359)
        at org.apache.hadoop.hbase.client.BufferedMutatorImpl.backgroundFlushCommits(BufferedMutatorImpl.java:238)
        at org.apache.hadoop.hbase.client.BufferedMutatorImpl.flush(BufferedMutatorImpl.java:190)
        at org.apache.hadoop.hbase.client.HTable.flushCommits(HTable.java:1498)
        at org.apache.hadoop.hbase.client.HTable.put(HTable.java:1094)
        at com.datamountaineer.streamreactor.connect.hbase.writers.HbaseWriter$$anonfun$insert$1$$anonfun$1.apply$mcV$sp(HbaseWriter.scala:104)
        at com.datamountaineer.streamreactor.connect.hbase.writers.HbaseWriter$$anonfun$insert$1$$anonfun$1.apply(HbaseWriter.scala:104)
        at com.datamountaineer.streamreactor.connect.hbase.writers.HbaseWriter$$anonfun$insert$1$$anonfun$1.apply(HbaseWriter.scala:104)
        at scala.util.Try$.apply(Try.scala:192)
        at com.datamountaineer.streamreactor.connect.hbase.writers.HbaseWriter$$anonfun$insert$1.apply(HbaseWriter.scala:104)
        at com.datamountaineer.streamreactor.connect.hbase.writers.HbaseWriter$$anonfun$insert$1.apply(HbaseWriter.scala:75)
        at scala.collection.immutable.Map$Map1.foreach(Map.scala:116)
```

4. I've checked the kafka-connect-hbase*.jar. It contains class org.apache.hadoop.hbase.util.ByteStringer. I don't why it throws java.lang.NoClassDefFoundError exception.

**Comment by artiship** [comment]
@AirTobe91 @stheppi 

Thanks. The problem is resolved. I Following @AirTobe91 's suggestion:

$CONFLUENT_HOME/etc/schema-registry/connect-avro-distributed.properties
change plugin.path from $STREAMREACTOR_HOME to$STREAMREACTOR_HOME/libs, 

then restart confluent. Kafka topic data sucessfully sinked to hbase table.

**Comment by scriperdjq** [comment]
Hi @artiship 

I have the same issue, the connector connects to localhost instead of remote,

INFO Process identifier=hconnection-0x4107c3fd connecting to ZooKeeper ensemble=localhost:2181 

As u had mentioned in the beginning of this thread, I had done the same setup. Can u let me know how to resolve this issue?

**Comment by artiship** [comment]
@scriperdjq 

I add hbase-site.xml to  CLASSPATH by export CLASSPATH=$CLASSPATH:~/hbase-site.xml, but the hbase sink connector can't find it. So I  just put hbase-site.xml into the jar file:

jar -uvf kafka-connect-hbase**.jar hbase-site.xml

and restart confluent. That sovles the problem.

**Comment by artiship** [comment]
@scriperdjq @stheppi
I think it's better to add a hbase.zookeeper.quorum property to task configuration

**Comment by scriperdjq** [comment]
@artiship Adding zookeeper.quorum to the configuration worked. Thanks.

**Comment by nishutayal** [comment]
@scriperdjq : Adding zookeeper.quorum to hbase-sink. properties didn't work for me.  I tried with hbase.zookeeper.quorum as well. It is pointing to localhost:2181 only. Adding hbase-site.xml to jar classpath works but I need some way to define in properties file. Can you provide some example?

**Comment by andrewstevenson** [comment]
@nishutayal An example of the hbase-site.xml? You can get this from your Hbase base cluster.

**Comment by scriperdjq** [comment]
@nishutayal I was wrong about that. @artiship solution of adding xml to jar was the one that worked.

**Comment by nishutayal** [comment]
@andrewstevenson  : Yeah, I am copying hbase-site.xml from hbase cluster and add in the hbase sink jar classpath, that solution is working perfectly.  
I was keen to know whether there is another way by defining the zookeeper as mentioned by  @scriperdjq to make it generalized in case of multiple hbase clusters. As we may have to maintain multiple jar files with different-2 hbase-site.xml so what can be the better solution?

@scriperdjq : Thanks for confirming.
