### ISSUE TITLE
kafka-connect-jms: JMSSessionProvider always attempts to produce AND consume from JMS Destinations

### ISSUE THREAD

**Issue by richardlundsky** [Landoop/stream-reactor#330]
When using the JMSSource to consume messages from an ActiveMQ broker, we observed the following:

```
[2017-11-24 08:44:27,877] ERROR Task sq-it-connector-0 threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask)
javax.jms.JMSSecurityException: User <SOME_USER> is not authorized to write to: topic://<SOME_TOPIC>
	at org.apache.activemq.util.JMSExceptionSupport.create(JMSExceptionSupport.java:52)
	at org.apache.activemq.ActiveMQConnection.syncSendPacket(ActiveMQConnection.java:1399)
	at org.apache.activemq.ActiveMQConnection.syncSendPacket(ActiveMQConnection.java:1428)
	at org.apache.activemq.ActiveMQSession.syncSendPacket(ActiveMQSession.java:2081)
	at org.apache.activemq.ActiveMQMessageProducer.<init>(ActiveMQMessageProducer.java:124)
	at org.apache.activemq.ActiveMQSession.createProducer(ActiveMQSession.java:1112)
	at com.datamountaineer.streamreactor.connect.jms.JMSSessionProvider$.createProducers(JMSSessionProvider.scala:113)
	at com.datamountaineer.streamreactor.connect.jms.JMSSessionProvider$$anonfun$4.apply(JMSSessionProvider.scala:99)
	at com.datamountaineer.streamreactor.connect.jms.JMSSessionProvider$$anonfun$4.apply(JMSSessionProvider.scala:99)
	at scala.collection.immutable.List.flatMap(List.scala:338)
	at com.datamountaineer.streamreactor.connect.jms.JMSSessionProvider$.apply(JMSSessionProvider.scala:99)
	at com.datamountaineer.streamreactor.connect.jms.source.readers.JMSReader.<init>(JMSReader.scala:36)
	at com.datamountaineer.streamreactor.connect.jms.source.readers.JMSReader$.apply(JMSReader.scala:65)
	at com.datamountaineer.streamreactor.connect.jms.source.JMSSourceTask.start(JMSSourceTask.scala:51)
	at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:142)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:146)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:190)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

After digging through the source it seems that there is a bug in `JMSSessionProvider` which will create a JMS Consumer **and** JMS Producer for every JMS Destination referenced. This behaviour causes the security exception above because the JMS Source is registering it's desire to produce messages to an ActiveMQ Topic that it does not have authorisation to.

**Comment by andrewstevenson** [comment]
@richardlundsky Yes, thats a valid bug. I put a fix in.

**Comment by richardlundsky** [comment]
@andrewstevenson Apologies if I've stepped on your toes here, I actually had the code ready when I reported the issue, but time constraints meant I only got round to raising the PR now.
