### ISSUE TITLE
Redis sink - Allow multiple primary keys

### ISSUE THREAD

**Issue by akir94** [Landoop/stream-reactor#333]
I'm trying out the redis sink, and I'm following the documentation [here](https://github.com/datamountaineer/docs/blob/master/source/redis.rst). I'm using the default setup for redis and the confluent platform, and redis-sink release 0.3.0.  However, the documentation doesn't match the behavior I actually see.

First, the example kcql causes an error, because it doesn't specify a primary key.
Second, the docs show that the example input is inserted with the key "John.Smith", but I can't replicate this behavior. The kcql "SELECT * FROM redis-topic PK firstName, lastName" causes an exception:

```
java.lang.AssertionError: assertion failed: The Redis CACHE mode requires strictly 1 PK (Primary Key) to be defined
        at scala.Predef$.assert(Predef.scala:170)
        at com.datamountaineer.streamreactor.connect.redis.sink.writer.RedisCache$$anonfun$3.apply(RedisCache.scala:45)
        at com.datamountaineer.streamreactor.connect.redis.sink.writer.RedisCache$$anonfun$3.apply(RedisCache.scala:43)
        at scala.collection.immutable.Set$Set1.foreach(Set.scala:94)
        at com.datamountaineer.streamreactor.connect.redis.sink.writer.RedisCache.<init>(RedisCache.scala:43)
        at com.datamountaineer.streamreactor.connect.redis.sink.RedisSinkTask$$anonfun$start$1.apply(RedisSinkTask.scala:72)
        at com.datamountaineer.streamreactor.connect.redis.sink.RedisSinkTask$$anonfun$start$1.apply(RedisSinkTask.scala:70)
        at scala.Option.map(Option.scala:146)
        at com.datamountaineer.streamreactor.connect.redis.sink.RedisSinkTask.start(RedisSinkTask.scala:70)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.initializeAndStart(WorkerSinkTask.java:232)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:145)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:146)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:190)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

```
Is the documentation outdated or am I doing something wrong?

**Comment by Antwnis** [comment]
Hi @akir94 

```The Redis CACHE mode requires strictly 1 PK (Primary Key) to be defined```

You seem to be using 2 PK 

Will have to check the code & documentation to review if defining multiple PK as in 

    PK firstName, lastName 

is supported

**Comment by stheppi** [comment]
@akir94 ,
  There is indeed this example in the documentation:
```INSERT INTO TABLE1 SELECT * FROM TOPIC1;INSERT INTO TABLE2 SELECT * FROM TOPIC2 PK field1, field2```
which uses two fields as PK.

At the moment the sink allows only one key. having multiple keys means we have to concatenate them. However this does not happen at the moment. We gladly accept contributions :).

**Comment by andrewstevenson** [comment]
@akir94 This has been fixed in master
