### ISSUE TITLE
influxdb plugin + flatten = IllegalArgumentException

### ISSUE THREAD

**Issue by FrancoisPoinsot** [Landoop/stream-reactor#337]
Hello, i have an issue using influxdb plugin with flatten transformation.

i am using 
 - kafka-connect-influxdb plugin realase 0.3.0 
 - kafka-connect 0.11.0.2
 - kafka 0.11.0.1
 - influxdb 1.3.7

config of connector : 
```
{
  "name": "influxdb-connector",
  "config": {
    "connector.class": "com.datamountaineer.streamreactor.connect.influx.InfluxSinkConnector",
    "tasks.max": 1,
    "topics": "topic-test",
    "connect.influx.kcql": "INSERT INTO index-test SELECT * FROM topic-test WITHTIMESTAMP sys_time()",
    "connect.influx.url": "http://influxdb-svc:8086",
    "connect.influx.db": "mydb",
    "connect.influx.username": "user1",
    "key.ignore": "false",
    "key.converter": "org.apache.kafka.connect.storage.StringConverter",
    "transforms":"flattenTime",
    "transforms.flattenTime.type":"org.apache.kafka.connect.transforms.Flatten$Value",
    "transforms.flattenTime.delimiter":"_"
  }
}
```

i get this error ouputed by kafka-connect:
```
java.lang.IllegalArgumentException: requirement failed: The SinkRecord payload should be of type java.util.Map[String, Any]
        at scala.Predef$.require(Predef.scala:224)
        at com.datamountaineer.streamreactor.connect.influx.writers.InfluxBatchPointsBuilder.buildPointFromMap(InfluxBatchPointsBuilder.scala:108)
        at com.datamountaineer.streamreactor.connect.influx.writers.InfluxBatchPointsBuilder.com$datamountaineer$streamreactor$connect$influx$writers$InfluxBatchPointsBuilder$$handleSinkRecord$1(InfluxBatchPointsBuilder.scala:78)
        at com.datamountaineer.streamreactor.connect.influx.writers.InfluxBatchPointsBuilder$$anonfun$build$1.apply(InfluxBatchPointsBuilder.scala:96)
        at com.datamountaineer.streamreactor.connect.influx.writers.InfluxBatchPointsBuilder$$anonfun$build$1.apply(InfluxBatchPointsBuilder.scala:96)
        at scala.collection.Iterator$class.foreach(Iterator.scala:891)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
        at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
        at com.datamountaineer.streamreactor.connect.influx.writers.InfluxBatchPointsBuilder.build(InfluxBatchPointsBuilder.scala:96)
        at com.datamountaineer.streamreactor.connect.influx.writers.InfluxDbWriter.write(InfluxDbWriter.scala:44)
        at com.datamountaineer.streamreactor.connect.influx.InfluxSinkTask$$anonfun$put$2.apply(InfluxSinkTask.scala:73)
        at com.datamountaineer.streamreactor.connect.influx.InfluxSinkTask$$anonfun$put$2.apply(InfluxSinkTask.scala:73)
        at scala.Option.foreach(Option.scala:257)
        at com.datamountaineer.streamreactor.connect.influx.InfluxSinkTask.put(InfluxSinkTask.scala:73)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:464)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:265)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:182)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:150)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:146)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:190)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
``` 

Without the last 3 lines about transform, it works fine. I get data in influx database.
Using the last 3 lines about transform in another basic file sink connector on the same kafka topic output what is expected:
```
{id=494d504f52543a3539313336313030393a4c697374696e67436c6173736966696564d41d8cd98f00b204e9800998ecf8427e, creation_date_seconds=1512035700}
```

so basically the two parts works correctly, separately.

connect-distributed.properties is
```
bootstrap.servers=broker1:9092,broker2:9092,broker3:9092
group.id=connect-cluster

key.converter=org.apache.kafka.connect.json.JsonConverter
value.converter=org.apache.kafka.connect.json.JsonConverter

key.converter.schemas.enable=false
value.converter.schemas.enable=false

internal.key.converter=org.apache.kafka.connect.json.JsonConverter
internal.value.converter=org.apache.kafka.connect.json.JsonConverter
internal.key.converter.schemas.enable=false
internal.value.converter.schemas.enable=false

offset.storage.topic=connect-offsets
offset.storage.replication.factor=3

config.storage.topic=connect-configs
config.storage.replication.factor=3

status.storage.topic=connect-status
status.storage.replication.factor=3

offset.flush.interval.ms=10000

plugin.path=/opt/kafka/plugins/
```

**Comment by Antwnis** [comment]
Have you tried flattening using `kcql` ?

    INSERT INTO index-test SELECT field1.x1 AS x1, field1.x2 AS x2, fieldN AS xn FROM topic-test WITHTIMESTAMP sys_time()

How are your original records looking like?

**Comment by FrancoisPoinsot** [comment]
original record look like
```
{"id":"494d504f52543a3539313336313030393a4c697374696e67436c6173736966696564d41d8cd98f00b204e9800998ecf8427e","creation_date":{"seconds":1512035700}}
```

**Comment by Antwnis** [comment]
Can u try

    INSERT INTO index-test SELECT id, creation_date.seconds AS mytime FROM topic-test WITHTIMESTAMP sys_time()

**Comment by FrancoisPoinsot** [comment]
```
java.lang.IllegalArgumentException: Invalid field selection for 'creation_date.seconds'. It doesn't resolve to a primitive field
        at com.datamountaineer.streamreactor.connect.influx.writers.ValuesExtractor$.checkValidPath$3(ValuesExtractor.scala:489)
        at com.datamountaineer.streamreactor.connect.influx.writers.ValuesExtractor$.innerExtract$3(ValuesExtractor.scala:507)
        at com.datamountaineer.streamreactor.connect.influx.writers.ValuesExtractor$.extract(ValuesExtractor.scala:515)
        at com.datamountaineer.streamreactor.connect.influx.writers.InfluxBatchPointsBuilder$$anonfun$buildPointFromMap$2$$anonfun$apply$5.apply(InfluxBatchPointsBuilder.scala:127)
        at com.datamountaineer.streamreactor.connect.influx.writers.InfluxBatchPointsBuilder$$anonfun$buildPointFromMap$2$$anonfun$apply$5.apply(InfluxBatchPointsBuilder.scala:127)
        at com.datamountaineer.streamreactor.connect.influx.writers.InfluxBatchPointsBuilder$$anonfun$com$datamountaineer$streamreactor$connect$influx$writers$InfluxBatchPointsBuilder$$buildPointFields$2.apply(InfluxBatchPointsBuilder.scala:259)
        at com.datamountaineer.streamreactor.connect.influx.writers.InfluxBatchPointsBuilder$$anonfun$com$datamountaineer$streamreactor$connect$influx$writers$InfluxBatchPointsBuilder$$buildPointFields$2.apply(InfluxBatchPointsBuilder.scala:254)
        at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
        at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
        at com.datamountaineer.streamreactor.connect.influx.writers.InfluxBatchPointsBuilder.com$datamountaineer$streamreactor$connect$influx$writers$InfluxBatchPointsBuilder$$buildPointFields(InfluxBatchPointsBuilder.scala:254)
        at com.datamountaineer.streamreactor.connect.influx.writers.InfluxBatchPointsBuilder$$anonfun$buildPointFromMap$2.apply(InfluxBatchPointsBuilder.scala:126)
        at com.datamountaineer.streamreactor.connect.influx.writers.InfluxBatchPointsBuilder$$anonfun$buildPointFromMap$2.apply(InfluxBatchPointsBuilder.scala:116)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.Iterator$class.foreach(Iterator.scala:891)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
        at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
        at scala.collection.AbstractTraversable.map(Traversable.scala:104)
        at com.datamountaineer.streamreactor.connect.influx.writers.InfluxBatchPointsBuilder.buildPointFromMap(InfluxBatchPointsBuilder.scala:116)
        at com.datamountaineer.streamreactor.connect.influx.writers.InfluxBatchPointsBuilder.com$datamountaineer$streamreactor$connect$influx$writers$InfluxBatchPointsBuilder$$handleSinkRecord$1(InfluxBatchPointsBuilder.scala:78)
        at com.datamountaineer.streamreactor.connect.influx.writers.InfluxBatchPointsBuilder$$anonfun$build$1.apply(InfluxBatchPointsBuilder.scala:96)
        at com.datamountaineer.streamreactor.connect.influx.writers.InfluxBatchPointsBuilder$$anonfun$build$1.apply(InfluxBatchPointsBuilder.scala:96)
        at scala.collection.Iterator$class.foreach(Iterator.scala:891)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
        at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
        at com.datamountaineer.streamreactor.connect.influx.writers.InfluxBatchPointsBuilder.build(InfluxBatchPointsBuilder.scala:96)
        at com.datamountaineer.streamreactor.connect.influx.writers.InfluxDbWriter.write(InfluxDbWriter.scala:44)
        at com.datamountaineer.streamreactor.connect.influx.InfluxSinkTask$$anonfun$put$2.apply(InfluxSinkTask.scala:73)
        at com.datamountaineer.streamreactor.connect.influx.InfluxSinkTask$$anonfun$put$2.apply(InfluxSinkTask.scala:73)
        at scala.Option.foreach(Option.scala:257)
        at com.datamountaineer.streamreactor.connect.influx.InfluxSinkTask.put(InfluxSinkTask.scala:73)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:464)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:265)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:182)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:150)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:146)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:190)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by stheppi** [comment]
@FrancoisPoinsot 
   I am looking at your records example and creation_date.seconds should be int. however, given the error that's not the case and somehow it resolves to a complex json node:array, objectnode.... can you confirm the record on kafka is the one above? 

  I put together a test with your data (see below) and it correctly sets the values.  You can try it yourself by adding the code into InfluxBatchPointsBuilderTest.
```scala
"test scenario of Francois" in {
      val jsonPayload =
        """
          | {
          |   "id":"494d504f52543a3539313336313030393a4c697374696e67436c6173736966696564d41d8cd98f00b204e9800998ecf8427e",
          |   "creation_date":{
          |     "seconds":1512035700
          |   }
          | }
          |
        """.
          stripMargin

      val topic = "topic1"
      val measurement = "measurement1"

      val before = nanoClock.getEpochNanos

      val record = new SinkRecord(topic, 0, null, null, Schema.STRING_SCHEMA, jsonPayload, 0)

      val settings = InfluxSettings("connection", "user", "password", "database1", "autogen", ConsistencyLevel.ALL,
        Seq(
          Kcql.parse(s"INSERT INTO $measurement SELECT id, creation_date.seconds FROM $topic")
        )
      )

      val builder = new InfluxBatchPointsBuilder(settings, nanoClock)
      val batchPoints = builder.build(Seq(record))
      val points = batchPoints.getPoints
      points.size() shouldBe 1
      val point = points.get(0)
      PointMapFieldGetter.measurement(point) shouldBe measurement
      val time = PointMapFieldGetter.time(point)
      before <= time shouldBe true
      time <= nanoClock.getEpochNanos shouldBe true

      val map = PointMapFieldGetter.fields(point)
      map.size shouldBe 2

      map.get("id") shouldBe "494d504f52543a3539313336313030393a4c697374696e67436c6173736966696564d41d8cd98f00b204e9800998ecf8427e"
      map.get("seconds") shouldBe "1512035700"

    }```

**Comment by FrancoisPoinsot** [comment]
Ok, i am not sure of what was happening. If i redo the all test on a clean influxdb i can use query with `creation_date.seconds` . 
Still not working with flatten transform though.

i guess this is an acceptable work around. I will do it that way

**Comment by stheppi** [comment]
@FrancoisPoinsot,
  We don't look at our SQL solution as a workaround. But rather the go to solution. Transfomers were added long after we had SQL in our connectors. We will enrich our SQL support to do more.
  We see the transformers setup decoupled and cumbersome to set-up. Imagine you had 5 topics sourcing your InfluxDb. And for each of those topics you had to set a transformer. Which one would read and configure easier: transformers or a friendly SQL syntax ?! 
 Good or bad we are the only ones providing easy conectors settings.
