### ISSUE TITLE
InfluxDB connector error

### ISSUE THREAD

**Issue by sachinkademane** [Landoop/stream-reactor#340]
Hi all, i am using stream reactor 3.3.0 ,confluent 4.0.0 and influxDB 1.3.5
I need to send data of json records from kafka stream API to InfluxDB through stream reactor.
My json records will be in the following format 

```
{"timestamp":"2017-12-05T13:52:43.560588466+05:30","namespace":"/intel/procfs/meminfo/active_anon","data":4183900160,"unit":"","tags":{"plugin_running_on":"AELAB110"},"version":4,"last_advertised_time":"2017-12-05T13:52:43.560658038+05:30"}
--
```
Whenever i try to do this my stream reactor is able to put only around 5 to 6 json records to influxDB and later when i check stream reactor status it will show the following error,

```
connectorState:  RUNNING 
workerId: 127.0.0.1:8083 
numberOfTasks: 1 tasks:   
- taskId: 0     taskState: FAILED     trace:  org.apache.kafka.connect.errors.ConnectException: Exiting WorkerSinkTask due to unrecoverable exception.         at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:517)         at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:288)         at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:198)         at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:166)         at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:170)         at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:214)         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)         at java.util.concurrent.FutureTask.run(FutureTask.java:266)         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)         at java.lang.Thread.run(Thread.java:748) Caused by: java.lang.NoSuchMethodError: okio.BufferedSource.rangeEquals(JLokio/ByteString;)Z         at okhttp3.internal.Util.bomAwareCharset(Util.java:431)         at okhttp3.ResponseBody.string(ResponseBody.java:174)         at org.influxdb.impl.InfluxDBImpl.execute(InfluxDBImpl.java:511)         at org.influxdb.impl.InfluxDBImpl.write(InfluxDBImpl.java:312)         at com.datamountaineer.streamreactor.connect.influx.writers.InfluxDbWriter$$anonfun$1.apply$mcV$sp(InfluxDbWriter.scala:46)         at com.datamountaineer.streamreactor.connect.influx.writers.InfluxDbWriter$$anonfun$1.apply(InfluxDbWriter.scala:46)         at com.datamountaineer.streamreactor.connect.influx.writers.InfluxDbWriter$$anonfun$1.apply(InfluxDbWriter.scala:46)         at scala.util.Try$.apply(Try.scala:192)         at com.datamountaineer.streamreactor.connect.influx.writers.InfluxDbWriter.write(InfluxDbWriter.scala:46)         at com.datamountaineer.streamreactor.connect.influx.InfluxSinkTask$$anonfun$put$2.apply(InfluxSinkTask.scala:73)         at com.datamountaineer.streamreactor.connect.influx.InfluxSinkTask$$anonfun$put$2.apply(InfluxSinkTask.scala:73)         at scala.Option.foreach(Option.scala:257)         at com.datamountaineer.streamreactor.connect.influx.InfluxSinkTask.put(InfluxSinkTask.scala:73)         at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:495)         ... 10 more      workerId: 127.0.0.1:8083
--
```
and it is showing caused by 

`Caused by: java.lang.NoSuchMethodError: okio.BufferedSource.rangeEquals(JLokio/ByteString;)Z
`
i am not understanding what is the problem and when i see influxDB 

```
[I] 2017-12-10T05:35:24Z write failed for shard 36: partial write: field type conflict: input field "data" on measurement "influxMeasure11" is type float, already exists as type integer dropped=36 service=write [httpd] 127.0.0.1 - root [10/Dec/2017:11:05:24 +0530] "POST /write?u=root&db=mydb&rp=autogen&precision=n&consistency=all HTTP/1.1" 400 147 "-" "okhttp/3.8.1" ebd238b9-dd6b-11e7-80c7-000000000000 33309
--
```

**Comment by stheppi** [comment]
@sachinkademane 
Looks like your data field can be Int and Float.  Since you are using a Json payload the sink has no clue that the incoming record which has now an int value later will have a float/double  value. hence the failure. We strongly advise you to use Avro if that is possible for you. Otherwise make sure you always have a float int the ``data``  field.
```
 field type conflict: input field "data" on measurement "influxMeasure11" is type float, already exists as type integer 
```

Now the ``NoSuchMethodError``. This should point you to classpath problems. We haven't released yet a version which we tested with Confluent  4.0  release. The github page says 3.3.1 dependency on our 3.0.0 release. You should check if you are using ``plugins.path`` and second if that is still not working you should see where you have a dependency on kio.BufferedSource because the jar already loaded has a different ``rangeEquals`` method than what the sink expects.
