### ISSUE TITLE
Issue with influxDB connector which is not able to put all metrics

### ISSUE THREAD

**Issue by sachinkademane** [Landoop/stream-reactor#345]
Hi, i am using stream reactor 3.3.0 and confluent kafka 4.0.0, the data from kafka should be put in to the influxDB.
Each and every second i will be getting data to kafka in the below format and below is not 6 seconds data, it is each seconds data so every second i will be getting 6 data at a time
```
{"timestamp":"2017-12-14T19:02:24.676937192+05:30","namespace":"/intel/iostat/avg-cpu/%idle","data":"100","unit":"","tags":{"plugin_running_on":"AELAB124"},"version":"0","last_advertised_time":"2017-12-14T19:02:24.676997308+05:30"}
{"timestamp":"2017-12-14T19:02:24.676970645+05:30","namespace":"/intel/iostat/avg-cpu/%system","data":"0","unit":"","tags":{"plugin_running_on":"AELAB124"},"version":"0","last_advertised_time":"2017-12-14T19:02:24.677000494+05:30"}
{"timestamp":"2017-12-14T19:02:24.676947119+05:30","namespace":"/intel/iostat/avg-cpu/%user","data":"0","unit":"","tags":{"plugin_running_on":"AELAB124"},"version":"0","last_advertised_time":"2017-12-14T19:02:24.676998472+05:30"}
{"timestamp":"2017-12-14T19:02:24.676991366+05:30","namespace":"/intel/iostat/avg-cpu/%iowait","data":"0","unit":"","tags":{"plugin_running_on":"AELAB124"},"version":"0","last_advertised_time":"2017-12-14T19:02:24.677001404+05:30"}
{"timestamp":"2017-12-14T19:02:24.676926255+05:30","namespace":"/intel/iostat/avg-cpu/%steal","data":"0","unit":"","tags":{"plugin_running_on":"AELAB124"},"version":"0","last_advertised_time":"2017-12-14T19:02:24.676991876+05:30"}
{"timestamp":"2017-12-14T19:02:24.676957094+05:30","namespace":"/intel/iostat/avg-cpu/%nice","data":"0","unit":"","tags":{"plugin_running_on":"AELAB124"},"version":"0","last_advertised_time":"2017-12-14T19:02:24.676999556+05:30"}
```
so if i send it to stream reactor to put all these data to influxDB , my stream reactor is able to put only 2 or 3 out of 6 in the above input.... every second my influxDB gets only 2 or max 3.
But if i put these data manually one by one instead of 6 at a time my stream reactor is able to put all data to influx..But my input is all of these 6 data come at a time every second

**Comment by Antwnis** [comment]
Please build the influxDB connector from the source code.
We have recently improved the accuracy to use Java's NANOSECOND method, to support better multiple entries / sec at commit https://github.com/Landoop/stream-reactor/commit/e8c6d247affa60c31b8b3318d21d9fe098440ef4 

We have not made a new release since then, so you will have to build from source code

**Comment by sachinkademane** [comment]
@Antwnis can u plzz tell me how to build from soucre code (e8c6d24)....is there any documentation for that?

**Comment by stheppi** [comment]
@sachinkademane 
  As it says on the readme file and is on the github project landing page do

```Building
gradle shadowJar
```

**Comment by Antwnis** [comment]
Checkout the project and 

    gradle :kafka-connect-influxdb:shadowJar

**Comment by sachinkademane** [comment]
https://github.com/Landoop/stream-reactor/tree/e8c6d247affa60c31b8b3318d21d9fe098440ef4 Is this the project which i need to build for that multiple entries support?

**Comment by Antwnis** [comment]
To checkout the project

    git clone https://github.com/Landoop/stream-reactor.git

**Comment by sachinkademane** [comment]
Thanks for the reply...if i do gradle compile
```
Starting a Gradle Daemon (subsequent builds will be faster)
> Configuring > 0/23 projects > root project > Resolving dependencies ':classpath'

```
resolving dependencies is not happening..nothing is coming up......

**Comment by Antwnis** [comment]
And if you do
 
    git clone https://github.com/Landoop/stream-reactor.git
    cd stream-reactor
    gradle :kafka-connect-influxdb:shadowJar
    
Then you can find the Connector at

    ls -la kafka-connect-influxdb/build/libs

**Comment by sachinkademane** [comment]
@Antwnis yea i did the same thing.......still it is not able to resolve dependencies....
```
[root@AELAB110 stream-reactor]# gradle :kafka-connect-influxdb:shadowJar
Starting a Gradle Daemon (subsequent builds will be faster)
> Configuring > 0/23 projects > root project > Resolving dependencies ':classpath'

```
even if i wait for 30 min ,nothing is coming up after this

**Comment by sachinkademane** [comment]
ok i built kafka-connect-influxdb....and then if i do 
`java -jar kafka-connect-influxdb-0.3.1-SNAPSHOT-3.3.0-all.jar create influx-sink < ../../../conf/influxdb-sink.properties
`
it shows the following error
`no main manifest attribute, in kafka-connect-influxdb-0.3.1-SNAPSHOT-3.3.0-all.jar`

**Comment by andrewstevenson** [comment]
@sachinkademane The connect is a plugin. You need to add it to your Kafka Connect cluster.

**Comment by sachinkademane** [comment]
@andrewstevenson Should i need to add that in my confluent or where exactly?

**Comment by sachinkademane** [comment]
@Antwnis @stheppi @andrewstevenson ok  i tried with what u said but whenever i try to check  status of my created influx-sink it is showing the following error..
```
[root@AELAB110 bin]# java -jar kafka-connect-cli-1.0.2-all.jar status influx-sink < ../conf/influxdb-sink.properties
connectorState:  RUNNING
workerId: 127.0.0.1:8083
numberOfTasks: 1
tasks:
  - taskId: 0
    taskState: FAILED
    trace:  java.lang.NoSuchMethodError: com.datamountaineer.kcql.Kcql.getDynamicTarget()Ljava/lang/String;
        at com.datamountaineer.streamreactor.connect.influx.writers.KcqlCache.<init>(InfluxBatchPointsBuilder.scala:336)
        at com.datamountaineer.streamreactor.connect.influx.writers.InfluxBatchPointsBuilder$$anonfun$5$$anonfun$apply$1.apply(InfluxBatchPointsBuilder.scala:70)
        at com.datamountaineer.streamreactor.connect.influx.writers.InfluxBatchPointsBuilder$$anonfun$5$$anonfun$apply$1.apply(InfluxBatchPointsBuilder.scala:53)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.Iterator$class.foreach(Iterator.scala:891)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
        at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
        at scala.collection.AbstractTraversable.map(Traversable.scala:104)
        at com.datamountaineer.streamreactor.connect.influx.writers.InfluxBatchPointsBuilder$$anonfun$5.apply(InfluxBatchPointsBuilder.scala:53)
        at com.datamountaineer.streamreactor.connect.influx.writers.InfluxBatchPointsBuilder$$anonfun$5.apply(InfluxBatchPointsBuilder.scala:48)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.immutable.Map$Map1.foreach(Map.scala:116)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
        at scala.collection.AbstractTraversable.map(Traversable.scala:104)
        at com.datamountaineer.streamreactor.connect.influx.writers.InfluxBatchPointsBuilder.<init>(InfluxBatchPointsBuilder.scala:48)
        at com.datamountaineer.streamreactor.connect.influx.writers.InfluxDbWriter.<init>(InfluxDbWriter.scala:37)
        at com.datamountaineer.streamreactor.connect.influx.writers.WriterFactoryFn$.apply(WriterFactoryFn.scala:33)
        at com.datamountaineer.streamreactor.connect.influx.InfluxSinkTask.start(InfluxSinkTask.scala:64)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.initializeAndStart(WorkerSinkTask.java:267)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:163)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:170)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:214)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
```
what does this error mean?

**Comment by Antwnis** [comment]
Can u also post the contents of `influxdb-sink.properties` ?

**Comment by andrewstevenson** [comment]
and the `connect.properties` for the worker?

**Comment by stheppi** [comment]
What is the name of the jar you built and copied to the Kafka connect folder to pick it up? The error points to a class path error which means there is a kcql version loaded which doesn't have the method with the signature it requires. 

How did you deploy?

**Comment by sachinkademane** [comment]
@Antwnis my influxdb-sink.properties looks like
```
connect.progress.enabled=true
name=influxdb-sink
connector.class=com.datamountaineer.streamreactor.connect.influx.InfluxSinkConnector
tasks.max=1
topics=intopic
connect.influx.kcql=INSERT INTO influxMeasure50 SELECT timestamp,namespace,data,unit,tags.plugin_running_on,version,last_advertised_time FROM intopic WITHTIMESTAMP sys_time()
connect.influx.url=http://10.224.54.99:8086
connect.influx.db=mydb
connect.influx.username=root
#connect.influx.password=root
```
@andrewstevenson  is it my connect-standalone.properties?

@stheppi before doing build of the new version of stream reactor i already had stream-reactor-0.3.0-3.3.0...so when i did `gradle :kafka-connect-influxdb:shadowJar` i got `kafka-connect-influxdb-0.3.1-SNAPSHOT-3.3.0-all.jar`...so this jar i copied it to my old stream-reactor-0.3.0-3.3.0/libs/ folder......it worked fine for me for a couple of times...but later i think i made some changes somewhere without my knowledge so this error is coming up....

**Comment by Antwnis** [comment]
@sachinkademane its a deployment issue, you have mixed different libs versions etc

Best to remove all connectors & keep only the only you built and restart Kafka Connect

**Comment by sachinkademane** [comment]
@Antwnis it's clearly not deployment issue....because i reset everything back in stream-reactor-0.3.0-3.3.0....so atleast it should work as normal right? But it is also showing the same error...

**Comment by sachinkademane** [comment]
@Antwnis @stheppi @andrewstevenson ok now it is working...but still multiple entries it is not able to support properly...if i give 12 entries at a time....my influxdb is taking only 5 or 6

**Comment by andrewstevenson** [comment]
@sachinkademane Are you still experiencing this issue?

**Comment by andrewstevenson** [comment]
No response so closing
