### ISSUE TITLE
Error retrieving Avro schema for id 1

### ISSUE THREAD

**Issue by junaidrazzaq323** [Landoop/stream-reactor#399]
Hi

`kafka-connect-cli-0.5-all.jar`
`cassandra 3.11.1`

**Connect-avro-distributed-properties:**

```
key.converter=io.confluent.connect.avro.AvroConverter
key.converter.schema.registry.url=http://localhost:8081
value.converter=io.confluent.connect.avro.AvroConverter
value.converter.schema.registry.url=http://localhost:8081

internal.key.converter=org.apache.kafka.connect.json.JsonConverter
internal.value.converter=org.apache.kafka.connect.json.JsonConverter
internal.key.converter.schemas.enable=false
internal.value.converter.schemas.enable=false
```

**Cassandra-sink-distributed-orders.properties:**

```
name=cassandra-sink-orders
connector.class=com.datamountaineer.streamreactor.connect.cassandra.sink.CassandraSinkConnector
tasks.max=1
topics=topic6
connect.cassandra.kcql=INSERT INTO o365_user_activity_by_date SELECT * FROM topic6
connect.cassandra.contact.points=localhost
connect.cassandra.port=9042
connect.cassandra.key.space=casb
connect.cassandra.contact.points=localhost
connect.cassandra.username=cassandra
connect.cassandra.password=cassandra
```

I am trying to write to a topic (Topic5) and then do stream processing and write to another topic (Topic6).
My Cassandra Sink Connector will put the record in Cassandra DB.

Streams Application code is very simple and is just acting as a Pipe.
**Pipe.java**
```
final StreamsBuilder builder = new StreamsBuilder();
builder.stream("topic5").to("topic6");
```

I am starting Connect using:

`bin/connect-distributed /etc/schema-registry/connect-avro-distributed.properties`

This is how I have created my Cassandra Table:

```
CREATE KEYSPACE casb WITH REPLICATION = { 'class' : 'SimpleStrategy', 'replication_factor' : 1 };
create table casb.o365_user_activity_by_date (
  current_date date,
  activity_time timestamp,
  user_id text,
  operation_type text,
  app_name text,
  PRIMARY KEY (current_date, activity_time)
)
WITH CLUSTERING ORDER BY (activity_time ASC);
```

Then I post my Cassandra Sink Configuration using:

`java -jar kafka-connect-cli-0.5-all.jar create cassandra-sink-orders < cassandra-sink-distributed-orders.properties`

I dont see any Errors in the terminal I started Connect API in and the connector configurations are posted successfully.

Then I am starting Streams Application, Kafka-Avro-Console-Producer and Kafka-Avro-Console-Consumer.

**Console-Producer:**

`kafka-avro-console-producer --broker-list localhost:9092 --topic topic5 --property value.schema='{"type":"record","name":"myrecord","fields":[{"name":"current_date", "type": "string"},{"name":"activity_time", "type": "string"}, {"name":"user_id", "type": "string"}, {"name":"operation_type", "type": "string"},{"name":"app_name", "type": "string"}]}'`

Next I send a JSON data by typing in the producer terminal:

`> {"current_date":"2018-02-15","activity_time":"2018-01-12T12:32:31","user_id":"omaji7@emumbaa10.onmicrosoft.com","operation_type":"AddedToGroup","app_name":"OneDrive"}`

After this an Error occurs.

**Traceback:**

```
[2018-02-15 18:00:59,971] ERROR WorkerSinkTask{id=cassandra-sink-orders-0} Task threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask:172)
org.apache.kafka.connect.errors.DataException: topic6
	at io.confluent.connect.avro.AvroConverter.toConnectData(AvroConverter.java:96)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.convertMessages(WorkerSinkTask.java:454)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:287)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:198)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:166)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:170)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:214)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.kafka.common.errors.SerializationException: Error retrieving Avro schema for id 1
Caused by: io.confluent.kafka.schemaregistry.client.rest.exceptions.RestClientException: Subject not found.; error code: 40401
	at io.confluent.kafka.schemaregistry.client.rest.RestService.sendHttpRequest(RestService.java:191)
	at io.confluent.kafka.schemaregistry.client.rest.RestService.httpRequest(RestService.java:218)
	at io.confluent.kafka.schemaregistry.client.rest.RestService.lookUpSubjectVersion(RestService.java:284)
	at io.confluent.kafka.schemaregistry.client.rest.RestService.lookUpSubjectVersion(RestService.java:272)
	at io.confluent.kafka.schemaregistry.client.CachedSchemaRegistryClient.getVersionFromRegistry(CachedSchemaRegistryClient.java:71)
	at io.confluent.kafka.schemaregistry.client.CachedSchemaRegistryClient.getVersion(CachedSchemaRegistryClient.java:182)
	at io.confluent.kafka.serializers.AbstractKafkaAvroDeserializer.deserialize(AbstractKafkaAvroDeserializer.java:152)
	at io.confluent.kafka.serializers.AbstractKafkaAvroDeserializer.deserializeWithSchemaAndVersion(AbstractKafkaAvroDeserializer.java:194)
	at io.confluent.connect.avro.AvroConverter$Deserializer.deserialize(AvroConverter.java:121)
	at io.confluent.connect.avro.AvroConverter.toConnectData(AvroConverter.java:84)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.convertMessages(WorkerSinkTask.java:454)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:287)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:198)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:166)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:170)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:214)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2018-02-15 18:00:59,973] ERROR WorkerSinkTask{id=cassandra-sink-orders-0} Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask:173)
[2018-02-15 18:00:59,974] INFO Stopping Cassandra sink. (com.datamountaineer.streamreactor.connect.cassandra.sink.CassandraSinkTask:79)
[2018-02-15 18:00:59,974] INFO Shutting down Cassandra driver session and cluster. (com.datamountaineer.streamreactor.connect.cassandra.sink.CassandraJsonWriter:253)

```

**Comment by Antwnis** [comment]
I am assuming your Kafka-Connect services have not been configured accordingly to contain a reference to the host/s where schema-registry is running

Also it would be helpful if you could share your ``cassandra-sink-distributed-orders.properties``

**Comment by junaidrazzaq323** [comment]
Thanks for all the help. I have reconfigured everything from scratch and
it's working now. I guess it was because of CLASSPATH env variable. However
on an other machine I was trying to create Cassandra connector and I get
SocketTimeoutException.

I read here that the connect rest API can timeout under load.

https://github.com/Landoop/kafka-connect-tools/issues/25

What does this mean? Kindly add some explanation to the comment by Andrew
Stevenson.

Thank you again for all the help.

Regards,
Junaid Razzaq
Data Engineer | eMumba

**Comment by Antwnis** [comment]
Maybe you need to set the CLASSPATH to the other machine as well ? and re-start connect service to pick it up ?

**Comment by junaidrazzaq323** [comment]
Yes I will try that and let you know.


Regards,
Junaid Razzaq

On Feb 19, 2018 12:03 AM, "Antonios Chalkiopoulos" <notifications@github.com>
wrote:

Maybe you need to set the CLASSPATH to the other machine as well ? and
re-start connect service to pick it up ?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Landoop/stream-reactor/issues/399#issuecomment-366538734>,
or mute the thread
