### ISSUE TITLE
HbaseSink for HBase lower version as 1.1.2

### ISSUE THREAD

**Issue by iMajna** [Landoop/stream-reactor#411]
# Issue Guidelines
As we are using Hbase on version 1.1.2 general connector of yours for Hbase version 1.2. didn't work for us. In order to make HbaseSink I downloaded your sourcecode and remake it a little bit (dependencies) so we can actually use the same sink. 

But well, full fatJar didn't work. There was missmatch of guava version: 
```
java.lang.IllegalAccessError: tried to access method com.google.common.base.Stopwatch.<init>()V from class org.apache.hadoop.hbase.zookeeper.MetaTableLocator
       at org.apache.hadoop.hbase.zookeeper.MetaTableLocator.blockUntilAvailable(MetaTableLocator.java:596)
       at org.apache.hadoop.hbase.zookeeper.MetaTableLocator.blockUntilAvailable(MetaTableLocator.java:580)
       at org.apache.hadoop.hbase.zookeeper.MetaTableLocator.blockUntilAvailable(MetaTableLocator.java:559)
       at org.apache.hadoop.hbase.client.ZooKeeperRegistry.getMetaRegionLocation(ZooKeeperRegistry.java:61)
```
As I was reading, **Stopwatch** method was removed in ``guava-17`` or so. 
Dependency tree of Hbase project with client version of 1.1.2 for the same looked like this: 

```
Task :kafka-connect-hbase:dependencyInsight

com.google.guava:guava:12.0.1 (forced)
+--- compile
+--- org.apache.hbase:hbase-client:1.1.2
|    \--- compile
+--- org.apache.hbase:hbase-common:1.1.2
|    \--- org.apache.hbase:hbase-client:1.1.2 (*)
\--- org.htrace:htrace-core:3.0.4
    +--- org.apache.hadoop:hadoop-hdfs:2.6.0
    |    \--- compile
    \--- org.apache.hadoop:hadoop-common:2.6.0
         \--- compile

com.google.guava:guava:11.0.2 -> 12.0.1
+--- org.apache.hadoop:hadoop-common:2.6.0
|    \--- compile
+--- org.apache.hadoop:hadoop-hdfs:2.6.0
|    \--- compile
+--- org.apache.hadoop:hadoop-yarn-api:2.5.1
|    \--- org.apache.hadoop:hadoop-yarn-common:2.5.1
|         \--- org.apache.hadoop:hadoop-mapreduce-client-core:2.5.1
|              +--- org.apache.hbase:hbase-client:1.1.2
|              |    \--- compile
|              \--- org.apache.hbase:hbase-common:1.1.2
|                  \--- org.apache.hbase:hbase-client:1.1.2 (*)
\--- org.apache.hadoop:hadoop-yarn-common:2.5.1 (*)

com.google.guava:guava:16.0.1 -> 12.0.1
+--- org.apache.curator:curator-client:2.6.0
|    +--- org.apache.hadoop:hadoop-common:2.6.0
|    |    \--- compile
|    \--- org.apache.curator:curator-framework:2.6.0
|         +--- org.apache.curator:curator-recipes:2.6.0
|         |    \--- org.apache.hadoop:hadoop-common:2.6.0 (*)
|         \--- org.apache.hadoop:hadoop-auth:2.6.0
|              +--- org.apache.hbase:hbase-client:1.1.2
|              |    \--- compile
|              \--- org.apache.hadoop:hadoop-common:2.6.0 (*)
+--- org.apache.curator:curator-framework:2.6.0 (*)
\--- org.apache.curator:curator-recipes:2.6.0 (*)

com.google.guava:guava:19.0 -> 12.0.1
\--- org.apache.calcite:calcite-core:1.12.0
    \--- com.landoop:sql-core_2.11:1.0
         \--- com.landoop:json-sql_2.11:1.0.1
              \--- com.landoop:kafka-connect-smt_2.11:1.0.0
                   \--- com.datamountaineer:kafka-connect-common:1.0.7
                        \--- compile

org.glassfish.jersey.bundles.repackaged:jersey-guava:2.25
\--- org.glassfish.jersey.core:jersey-common:2.25
    +--- org.glassfish.jersey.ext:jersey-bean-validation:2.25
    |    +--- io.confluent:kafka-schema-registry:4.0.0
    |    |    \--- compile
    |    \--- io.confluent:rest-utils:4.0.0
    |         \--- io.confluent:kafka-schema-registry:4.0.0 (*)
    +--- org.glassfish.jersey.containers:jersey-container-servlet:2.25
    |    \--- io.confluent:rest-utils:4.0.0 (*)
    +--- org.glassfish.jersey.containers:jersey-container-servlet-core:2.25
    |    \--- org.glassfish.jersey.containers:jersey-container-servlet:2.25 (*)
    +--- org.glassfish.jersey.core:jersey-server:2.25
    |    +--- org.glassfish.jersey.ext:jersey-bean-validation:2.25 (*)
    |    +--- org.glassfish.jersey.containers:jersey-container-servlet:2.25 (*)
    |    \--- org.glassfish.jersey.containers:jersey-container-servlet-core:2.25 (*)
    +--- org.glassfish.jersey.core:jersey-client:2.25
    |    \--- org.glassfish.jersey.core:jersey-server:2.25 (*)
    \--- org.glassfish.jersey.media:jersey-media-jaxb:2.25
         \--- org.glassfish.jersey.core:jersey-server:2.25 (*)

(*) - dependencies omitted (listed previously)
```
Which was showing me that the ``guava`` version was exactly as needed or on version 12 as it is forced in project build. 
Afterwards on @andmarios  suggestion I tried to make jar with separate dependency folder and set the same in ``plugin.path``. It worked. 
In theory it should work with fatJar but it didn't  start. First thing when I separate dependencies from jar it worked. I can share whole build or make a PR, but I'm not seeing why with fatjar sinker is not working.

**Comment by andrewstevenson** [comment]
Closing as we won't back port
