### ISSUE TITLE
MqttSourceConnector: WITHCONVERTER is ignored when WITHREGEX is provided.

### ISSUE THREAD

**Issue by Nieknikey** [Landoop/stream-reactor#420]
When providing `WITHREGEX` in the KCQL string, the provided `WITHCONVERTER` is ignored. As a result, the connector falls back to default converter (BytesConverter).

Reproduce this by configuring an MqttSourceConnector and using a KCQL string with both `WITHREGEX` and `WITHCONVERTER` arguments. [At this line](https://github.com/Landoop/stream-reactor/blob/master/kafka-connect-mqtt/src/main/scala/com/datamountaineer/streamreactor/connect/mqtt/config/MqttSourceSettings.scala#L86), `k.getWithConverter` will evaluate to `null`, while it should evaluate to the provided `WITHCONVERTER` converter.

**Comment by stheppi** [comment]
@Nieknikey 
This is part of KCQL testing:
``` public void handleWithRegex() {
    String topic = "/TOPIC_A";
    String table = "TABLE_A";
    String syntax = String.format("INSERT INTO %s SELECT col1,col2 FROM %s WITHCONVERTER=`com.blah.Converter` WITHREGEX=`/^#?([a-f0-9]{6}|[a-f0-9]{3})$/`", table, topic);
    Kcql kcql = Kcql.parse(syntax);
    assertEquals("/^#?([a-f0-9]{6}|[a-f0-9]{3})$/", kcql.getWithRegex());
    assertEquals("com.blah.Converter", kcql.getWithConverter());
  }```

and it is green. are you not escaping your regex?

**Comment by Nieknikey** [comment]
I've provided an escaped regex. I changed [this line](https://github.com/Landoop/stream-reactor/blob/master/kafka-connect-mqtt/src/main/scala/com/datamountaineer/streamreactor/connect/mqtt/config/MqttSourceSettings.scala#L86) to the following, for debugging purposes:
```scala
val converters = kcql.map(k => {
      (k.getSource, if (k.getWithConverter == null) {
        throw new ConfigException("BUG FOUND!")
        classOf[BytesConverter].getCanonicalName
      } else k.getWithConverter)
    }).toMap
```
The exception I added there, is thrown. The following log includes the used config and the exception that is thrown.
```
[2018-03-30 09:14:11,914] INFO MqttSourceConfig values: 
        connect.converter.avro.schemas = 
        connect.mqtt.clean = true
        connect.mqtt.client.id = vmq01_src_con
        connect.mqtt.converter.throw.on.error = true
        connect.mqtt.error.policy = THROW
        connect.mqtt.hosts = wss://ec2-52-59-193-60.eu-central-1.compute.amazonaws.com:443
        connect.mqtt.kcql = INSERT INTO glue-pilot SELECT * FROM `$share/kafka_clients/p1dongles/+/smartmeter/electricity/+` WITHREGEX=`p1dongles/[^/]+/smartmeter/electricity/[^/]+` WITHCONVERTER=`com.nsure_technologies.devicegateway.connect.MqttConverte
r` WITHKEY (`p1dongles/[^/]+/smartmeter/electricity/([^/]+)`)
        connect.mqtt.keep.alive = 5000
        connect.mqtt.max.retries = 20
        connect.mqtt.password = null
        connect.mqtt.polling.timeout = 1000
        connect.mqtt.retry.interval = 60000
        connect.mqtt.service.quality = 2
        connect.mqtt.ssl.ca.cert = /etc/ssl/certs/mqttclient/server_ca_cert.pem
        connect.mqtt.ssl.cert = /etc/ssl/certs/mqttclient/client_cert.pem
        connect.mqtt.ssl.key = /etc/ssl/certs/mqttclient/client_pk.pem
        connect.mqtt.timeout = 3000
        connect.mqtt.username = null
        connect.progress.enabled = true
 (com.datamountaineer.streamreactor.connect.mqtt.config.MqttSourceConfig:238)
[2018-03-30 09:14:11,914] ERROR Failed to reconfigure connector's tasks, retrying after backoff: (org.apache.kafka.connect.runtime.distributed.DistributedHerder:944)
org.apache.kafka.common.config.ConfigException: BUG FOUND!
        at com.datamountaineer.streamreactor.connect.mqtt.config.MqttSourceSettings$$anonfun$3.apply(MqttSourceSettings.scala:87)
        at com.datamountaineer.streamreactor.connect.mqtt.config.MqttSourceSettings$$anonfun$3.apply(MqttSourceSettings.scala:85)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.immutable.Set$Set1.foreach(Set.scala:94)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
        at scala.collection.AbstractSet.scala$collection$SetLike$$super$map(Set.scala:47)
        at scala.collection.SetLike$class.map(SetLike.scala:92)
        at scala.collection.AbstractSet.map(Set.scala:47)
        at com.datamountaineer.streamreactor.connect.mqtt.config.MqttSourceSettings$.apply(MqttSourceSettings.scala:85)
        at com.datamountaineer.streamreactor.connect.mqtt.source.MqttSourceConnector.taskConfigs(MqttSourceConnector.scala:49)
        at org.apache.kafka.connect.runtime.Worker.connectorTaskConfigs(Worker.java:274)
        at org.apache.kafka.connect.runtime.distributed.DistributedHerder.reconfigureConnector(DistributedHerder.java:986)
        at org.apache.kafka.connect.runtime.distributed.DistributedHerder.reconfigureConnectorTasksWithRetry(DistributedHerder.java:936)
        at org.apache.kafka.connect.runtime.distributed.DistributedHerder.access$900(DistributedHerder.java:108)
        at org.apache.kafka.connect.runtime.distributed.DistributedHerder$17$1.call(DistributedHerder.java:949)
        at org.apache.kafka.connect.runtime.distributed.DistributedHerder$17$1.call(DistributedHerder.java:946)
        at org.apache.kafka.connect.runtime.distributed.DistributedHerder.tick(DistributedHerder.java:261)
        at org.apache.kafka.connect.runtime.distributed.DistributedHerder.run(DistributedHerder.java:210)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
[2018-03-30 09:14:11,914] ERROR Unexpected error during connector task reconfiguration:  (org.apache.kafka.connect.runtime.distributed.DistributedHerder:955)
[2018-03-30 09:14:11,915] ERROR Task reconfiguration for vmq01_source failed unexpectedly, this connector will not be properly reconfigured unless manually triggered. (org.apache.kafka.connect.runtime.distributed.DistributedHerder:956)
```

If I remove the ``WITHREGEX``, the ``WITHCONVERTER`` is parsed correctly.

**Comment by stheppi** [comment]
```
INSERT INTO ABC SELECT * 
FROM abc  
       WITHCONVERTER=`com.nsure_technologies.devicegateway.connect.MqttConverter` 
        WITHREGEX=`p1dongles/[^/]+/smartmeter/electricity/[^/]+`
        WITHKEY (`p1dongles/[^/]+/smartmeter/electricity/([^/]+)`);

```

Look at the order. the order matters. we have it on the road map to not require a strict order.
