### ISSUE TITLE
Multiple SortedSet in Redis sink not working

### ISSUE THREAD

**Issue by ragnor** [Landoop/stream-reactor#437]
# Issue Guidelines

Please review these questions before submitting any issue?

### What version of the Stream Rector are you reporting this issue for?
1.0.0

### Are you running the correct version of Kafka/Confluent for the Stream reactor release?
Yes, kafka 2.12-1.0.0

### Have you consulted our [FAQs](http://docs.datamountaineer.com/en/latest/faq.html) page first?
Yes, I have.

### Do you have a supported version of the data source/sink .i.e Cassandra 3.0.9?
I hope so but the exception occurs when connect's configuration is parsed before trying to connect to redis.

### Have you read the [docs](http://lenses.stream/connectors/index.html)?
Yes, I have.

### What is the expected behaviour?
Connect to redis instance.

### What was observed?
An exception occurs when a kcql from manual (_SELECT temperature, humidity FROM sensorsTopic PK sensorID STOREAS SortedSet(score=timestamp)_) is used:
```
[2018-05-08 15:05:56,586] ERROR WorkerSinkTask{id=redis-signals-sink-0} Task threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask)
java.lang.NullPointerException
        at com.datamountaineer.streamreactor.connect.redis.sink.RedisSinkTask$$anonfun$4.apply(RedisSinkTask.scala:66)
        at com.datamountaineer.streamreactor.connect.redis.sink.RedisSinkTask$$anonfun$4.apply(RedisSinkTask.scala:66)
        at scala.collection.TraversableLike$$anonfun$filterImpl$1.apply(TraversableLike.scala:248)
        at scala.collection.immutable.Set$Set1.foreach(Set.scala:94)
        at scala.collection.TraversableLike$class.filterImpl(TraversableLike.scala:247)
        at scala.collection.TraversableLike$class.filter(TraversableLike.scala:259)
        at scala.collection.AbstractTraversable.filter(Traversable.scala:104)
        at com.datamountaineer.streamreactor.connect.redis.sink.RedisSinkTask.start(RedisSinkTask.scala:66)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.initializeAndStart(WorkerSinkTask.java:267)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:163)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:170)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:214)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
[2018-05-08 15:05:56,589] ERROR WorkerSinkTask{id=redis-sink-0} Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask)
```
I can run sink in cache and sorted set mode but not in multiple sorted set mode. 
When trying to set a prefix: _INSERT INTO SENSOR- SELECT temperature, humidity FROM sensorsTopic PK sensorID STOREAS SortedSet(score=timestamp)_ there is a different exception:
```
java.lang.AssertionError: assertion failed: They keyword PK (Primary Key) is not supported in Redis INSERT_SS mode. Please review the KCQL syntax of connector
        at scala.Predef$.assert(Predef.scala:170)
        at com.datamountaineer.streamreactor.connect.redis.sink.writer.RedisInsertSortedSet$$anonfun$3.apply(RedisInsertSortedSet.scala:50)
        at com.datamountaineer.streamreactor.connect.redis.sink.writer.RedisInsertSortedSet$$anonfun$3.apply(RedisInsertSortedSet.scala:45)
        at scala.collection.immutable.Set$Set1.foreach(Set.scala:94)
        at com.datamountaineer.streamreactor.connect.redis.sink.writer.RedisInsertSortedSet.<init>(RedisInsertSortedSet.scala:45)
        at com.datamountaineer.streamreactor.connect.redis.sink.RedisSinkTask$$anonfun$start$2.apply(RedisSinkTask.scala:77)
        at com.datamountaineer.streamreactor.connect.redis.sink.RedisSinkTask$$anonfun$start$2.apply(RedisSinkTask.scala:75)
        at scala.Option.map(Option.scala:146)
        at com.datamountaineer.streamreactor.connect.redis.sink.RedisSinkTask.start(RedisSinkTask.scala:75)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.initializeAndStart(WorkerSinkTask.java:267)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:163)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:170)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:214)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

### What is your Connect cluster configuration (connect-avro-distributed.properties)?
I've tried it in a standalone mode.

### What is your connector properties configuration (my-connector.properties)?
name=redis-sink
connector.class=com.datamountaineer.streamreactor.connect.redis.sink.RedisSinkConnector
tasks.max=1
topics=sensorsTopic
connect.redis.host=127.0.0.1
connect.redis.port=6379
connect.redis.kcql=SELECT temperature, humidity FROM sensorsTopic PK sensorID STOREAS SortedSet(score=timestamp)

**Comment by polyzosG** [comment]
this is a bug and hopefully the next release will include a fix on it

**Comment by Antwnis** [comment]
@ragnor If you check out and build from source, this has now been addressed and should work as documented. If any issues please re-open this ticket. Thanks for reporting it

**Comment by ragnor** [comment]
Thanks for the quick fix. 
I confirm that it works correctly for both sentences (SELECT and INSERT-SELECT).

Could you please clarify for me if redis-sink can take as an input kafka messages serialized to JSON? I've browsed through the code and it seams that only Avro is supported. Am I right?

BTW The shadowJar gradle task for kafka-redis-connect doesn't include in fat/uber jar all required dependencies which leads to an exception during startup:
```
SEVERE: Error loading factory org.apache.calcite.jdbc.CalciteJdbc41Factory
java.lang.NoClassDefFoundError: org/apache/calcite/linq4j/QueryProvider
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at org.apache.kafka.connect.runtime.isolation.PluginClassLoader.loadClass(PluginClassLoader.java:96)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at org.apache.kafka.connect.runtime.isolation.PluginClassLoader.loadClass(PluginClassLoader.java:96)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at org.apache.kafka.connect.runtime.isolation.PluginClassLoader.loadClass(PluginClassLoader.java:96)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at org.apache.calcite.avatica.UnregisteredDriver.instantiateFactory(UnregisteredDriver.java:115)
        at org.apache.calcite.avatica.UnregisteredDriver.createFactory(UnregisteredDriver.java:74)
        at org.apache.calcite.avatica.UnregisteredDriver.<init>(UnregisteredDriver.java:55)
        at org.apache.calcite.jdbc.Driver.<init>(Driver.java:60)
        at org.apache.calcite.jdbc.Driver.<clinit>(Driver.java:56)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at java.lang.Class.newInstance(Class.java:442)
        at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:380)
        at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
        at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
        at org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader$2.run(DelegatingClassLoader.java:249)
        at org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader$2.run(DelegatingClassLoader.java:240)
        at java.security.AccessController.doPrivileged(Native Method)
        at org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader.loadJdbcDrivers(DelegatingClassLoader.java:239)
        at org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader.scanUrlsAndAddPlugins(DelegatingClassLoader.java:233)
        at org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader.registerPlugin(DelegatingClassLoader.java:208)
        at org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader.initPluginLoader(DelegatingClassLoader.java:177)
        at org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader.initLoaders(DelegatingClassLoader.java:154)
        at org.apache.kafka.connect.runtime.isolation.Plugins.<init>(Plugins.java:56)
        at org.apache.kafka.connect.cli.ConnectStandalone.main(ConnectStandalone.java:77)
Caused by: java.lang.ClassNotFoundException: org.apache.calcite.linq4j.QueryProvider
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at org.apache.kafka.connect.runtime.isolation.PluginClassLoader.loadClass(PluginClassLoader.java:104)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 58 more
```

Modifying the fat jar and adding manually content of calcite-linq4j resolves the issue.

**Comment by Rdebokx** [comment]
Alternatively you can use the following dependencies in [kafka-connect-redis/build.gradle](https://github.com/Landoop/stream-reactor/blob/master/kafka-connect-redis/build.gradle) and rebuild the shadowJar.

```
dependencies {
        compile "org.apache.calcite:calcite-linq4j:$link4jVersion"
        compile "redis.clients:jedis:$jedisVersion"
        testCompile "com.google.code.gson:gson:$gsonVersion"
        testCompile "com.orange.redis-embedded:embedded-redis:$embeddedRedisVersion"
    }
```
Where I used `link4jVersion = "1.8.0"`

I'm not sure if this is the desired solution, however, so I have not submitted this as a PR.

**Comment by stheppi** [comment]
I would add this dependency in the main project gradle such that all sinks/sources get this
