### ISSUE TITLE
JsonSimpleConverter throws java java.util.NoSuchElementException: head of empty list

### ISSUE THREAD

**Issue by ryan2x** [Landoop/stream-reactor#444]
It seems that arr can be an empty list. So I add these lines and it seems to fix the problem:

        if (arr.isEmpty) {
          return new SchemaAndValue(Schema.STRING_SCHEMA, null)
        }

Is that the right correct fix?

**Comment by stheppi** [comment]
@ryan2x  Please provide the error stack and the context.
the above looks like a hack. you have an array and you return a Schema of String

**Comment by stheppi** [comment]
There are many reasons why arr can be empty. It would be good to understand the context. Avoid hacks without providing the why it happens

**Comment by ryan2x** [comment]
Thanks for your fast response. Here is the crash stack. I was wondering why the array is empty. The message is from MQTT.
java.util.NoSuchElementException: head of empty list
        at scala.collection.immutable.Nil$.head(List.scala:431)
        at scala.collection.immutable.Nil$.head(List.scala:428)
        at com.datamountaineer.streamreactor.connect.converters.source.JsonSimpleConverter$.convert(JsonSimpleConverter.scala:76)
        at com.datamountaineer.streamreactor.connect.converters.source.JsonSimpleConverter$$anonfun$2.apply(JsonSimpleConverter.scala:95)
        at com.datamountaineer.streamreactor.connect.converters.source.JsonSimpleConverter$$anonfun$2.apply(JsonSimpleConverter.scala:94)
        at scala.collection.immutable.List.map(List.scala:288)
        at com.datamountaineer.streamreactor.connect.converters.source.JsonSimpleConverter$.convert(JsonSimpleConverter.scala:94)
        at com.datamountaineer.streamreactor.connect.converters.source.JsonSimpleConverter$.convert(JsonSimpleConverter.scala:70)
        at com.datamountaineer.streamreactor.connect.converters.source.JsonSimpleConverter.convert(JsonSimpleConverter.scala:37)
        at com.datamountaineer.streamreactor.connect.mqtt.source.MqttManager.messageArrived(MqttManager.scala:73)

**Comment by polyzosG** [comment]
JsonSimpleConverter is a best effort to convert from an incoming JSON to a Connect Struct which leads to Avro records into your Kafka topic if you are using AvroConverter for your connector instance.  Your suggested fix is not applicable to this generic converter, but more over you should plug in your own converter for best performance but also because of the following scenario:
 - Json payload 1: {... "value":10,...} 
 - Json payload 2:{... "value":999999999999,...}
 For the two entries above two different schemas will end up being created. You are know your domain so you know your payload best therefore you should write a converter to match that. We have users and customers who have done that. All you need to do is reference `com.datamountaineer:kafka-connect-common:` and implement `com.datamountaineer.streamreactor.connect.converters.source.Converter`. And the resulting jar needs to be part of your `plugin.path` location. Part of our services we do client engagements like this should you require.

**Comment by ryan2x** [comment]
I did exactly what you said: I patched empty array situation in the original JsonSimpleConverter and created my own "JsonPatchedSimpleConverter", and use this class as a customized convert, and it works well. Problem solved.

You guys are doing a wonderful job by providing the community source/sink adaptors. Thanks!
