### ISSUE TITLE
Kafka-connect-Redis-1.1.0: multiple topics issue

### ISSUE THREAD

**Issue by sguarrinieye** [Landoop/stream-reactor#449]
I'm testing the latest version (1.1.0) of Kafka-Redis connector on Confluent 4.1.0 and on the latest stable Redis version (4.0.9).
Everything's okey if you launch the connector on a single topic (Cache mode) but something goes wrong if you try with 2 (and maybe more) topics.

Connector Properties example:

> name=connectorTest
> connector.class=com.datamountaineer.streamreactor.connect.redis.sink.RedisSinkConnector
> topics=topic1,topic2
> connect.redis.host=localhost
> connect.redis.port=6379
> connect.redis.kcql=INSERT INTO prefix1: SELECT * FROM topic1 PK id; INSERT INTO prefix2: SELECT * FROM topic2 PK id

This is the full log:

> java.lang.IndexOutOfBoundsException: 1
> 	at scala.collection.mutable.ResizableArray$class.apply(ResizableArray.scala:43)
> 	at scala.collection.mutable.ArrayBuffer.apply(ArrayBuffer.scala:48)
> 	at com.datamountaineer.streamreactor.connect.redis.sink.config.RedisSinkSettings$$anonfun$2.apply(RedisSinkSettings.scala:70)
> 	at com.datamountaineer.streamreactor.connect.redis.sink.config.RedisSinkSettings$$anonfun$2.apply(RedisSinkSettings.scala:69)
> 	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
> 	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
> 	at scala.collection.immutable.Range.foreach(Range.scala:160)
> 	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
> 	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
> 	at com.datamountaineer.streamreactor.connect.redis.sink.config.RedisSinkSettings$.apply(RedisSinkSettings.scala:69)
> 	at com.datamountaineer.streamreactor.connect.redis.sink.RedisSinkTask.start(RedisSinkTask.scala:53)
> 	at org.apache.kafka.connect.runtime.WorkerSinkTask.initializeAndStart(WorkerSinkTask.java:281)
> 	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:170)
> 	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:170)
> 	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:214)
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 	at java.lang.Thread.run(Thread.java:748)

Is this a bug or I'm missing something? Thanks

**Comment by andrewstevenson** [comment]
@sguarrinieye Yup, this is a bug, we'll have a fix on master by tomorrow.

**Comment by andrewstevenson** [comment]
@sguarrinieye PR pending https://github.com/Landoop/stream-reactor/pull/446

**Comment by Antwnis** [comment]
Merged in master 
@sguarrinieye can you build the code from master and retry and see if we can close this issue ?

**Comment by sguarrinieye** [comment]
@Antwnis @andrewstevenson Thanks guys. The changes are not in master yet but I've built the connector from 
> bug/redis-multiple-kcql

No problem at the launch now, but when you start to receive messages from Kafka everything's okey from the first topic until you start to receive something from the second topic simultaneously. This is the error:

> org.apache.kafka.connect.errors.DataException: my_topic
	at io.confluent.connect.avro.AvroConverter.toConnectData(AvroConverter.java:95)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.convertMessages(WorkerSinkTask.java:468)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:301)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:205)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:173)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:170)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:214)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.kafka.common.errors.SerializationException: Error retrieving Avro schema for id 21
Caused by: io.confluent.kafka.schemaregistry.client.rest.exceptions.RestClientException: Schema not found; error code: 40403
	at io.confluent.kafka.schemaregistry.client.rest.RestService.sendHttpRequest(RestService.java:202)
	at io.confluent.kafka.schemaregistry.client.rest.RestService.httpRequest(RestService.java:229)
	at io.confluent.kafka.schemaregistry.client.rest.RestService.lookUpSubjectVersion(RestService.java:296)
	at io.confluent.kafka.schemaregistry.client.rest.RestService.lookUpSubjectVersion(RestService.java:284)
	at io.confluent.kafka.schemaregistry.client.CachedSchemaRegistryClient.getVersionFromRegistry(CachedSchemaRegistryClient.java:125)
	at io.confluent.kafka.schemaregistry.client.CachedSchemaRegistryClient.getVersion(CachedSchemaRegistryClient.java:236)
	at io.confluent.kafka.serializers.AbstractKafkaAvroDeserializer.deserialize(AbstractKafkaAvroDeserializer.java:152)
	at io.confluent.kafka.serializers.AbstractKafkaAvroDeserializer.deserializeWithSchemaAndVersion(AbstractKafkaAvroDeserializer.java:194)
	at io.confluent.connect.avro.AvroConverter$Deserializer.deserialize(AvroConverter.java:120)
	at io.confluent.connect.avro.AvroConverter.toConnectData(AvroConverter.java:83)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.convertMessages(WorkerSinkTask.java:468)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:301)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:205)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:173)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:170)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:214)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Of course the schema is there like the other one. Any idea?

**Comment by stheppi** [comment]
`Caused by: org.apache.kafka.common.errors.SerializationException: Error retrieving Avro schema for id 21`

Somehow it doesn't find the schema with id 21. you should check if you have 21 in your schema registry.
the error is in the Connect framework stack not in the connector code.

**Comment by sguarrinieye** [comment]
@stheppi You're right! Double checked that. Thank you. @Antwnis You can close it
