### ISSUE TITLE
kafka-connect-mongodb sink exception when PK is compound key

### ISSUE THREAD

**Issue by invadergir** [Landoop/stream-reactor#450]
Logs and configurations are here: [mongo-sink-compound-key-exception.zip](https://github.com/Landoop/stream-reactor/files/2055809/mongo-sink-compound-key-exception.zip)

### What version of the Stream Rector are you reporting this issue for?
1.1.0+, master commit 4232f11e124cd9e1b86a4f5ce076592a6dcf2a50

### Are you running the correct version of Kafka/Confluent for the Stream reactor release?
Yes 1.1.0

### Have you consulted our [FAQs](http://docs.datamountaineer.com/en/latest/faq.html) page first?
Dead link - redirects to lenses

### Do you have a supported version of the data source/sink .i.e Cassandra 3.0.9?
Yes, mongodb 3.6.4

### Have you read the [docs](http://lenses.stream/connectors/index.html)?
Yes

### What is the expected behaviour?
Using this kcql for mongo sink:  
```
    UPSERT INTO coll SELECT * FROM test PK zoneId,data2
```
I would expect the data inserted into mongodb to have a key that looks like this:
```
    { "zoneId": "...", "data2": "..." }
```

### What was observed?
The connector throws an exception (for full details, see kafka-connector-log.txt in attached zipfile for details).
The log and partial stack is: 
```
[2018-05-30 16:46:41,574] ERROR There was an error inserting the records Bulk write operation error on server localhost:27017. Write errors: [BulkWriteError{index=0, code=111, message='field at '_id' must be exactly specified, field at sub-path '_id.data2'found', details={ }}].  (com.datamountaineer.streamreactor.connect.mongodb.sink.MongoWriter:120)
com.mongodb.MongoBulkWriteException: Bulk write operation error on server localhost:27017. Write errors: [BulkWriteError{index=0, code=111, message='field at '_id' must be exactly specified, field at sub-path '_id.data2'found', details={ }}]. 
        at com.mongodb.connection.BulkWriteBatchCombiner.getError(BulkWriteBatchCombiner.java:176)
        at com.mongodb.connection.BulkWriteBatchCombiner.throwOnError(BulkWriteBatchCombiner.java:205)
        at com.mongodb.connection.BulkWriteBatchCombiner.getResult(BulkWriteBatchCombiner.java:146)
        at com.mongodb.operation.BulkWriteBatch.getResult(BulkWriteBatch.java:219)
        at com.mongodb.operation.MixedBulkWriteOperation.executeBulkWriteBatch(MixedBulkWriteOperation.java:265)
        at com.mongodb.operation.MixedBulkWriteOperation.access$700(MixedBulkWriteOperation.java:65)
        at com.mongodb.operation.MixedBulkWriteOperation$1.call(MixedBulkWriteOperation.java:198)
        at com.mongodb.operation.MixedBulkWriteOperation$1.call(MixedBulkWriteOperation.java:189)
        at com.mongodb.operation.OperationHelper.withReleasableConnection(OperationHelper.java:433)
        at com.mongodb.operation.MixedBulkWriteOperation.execute(MixedBulkWriteOperation.java:189)
        at com.mongodb.operation.MixedBulkWriteOperation.execute(MixedBulkWriteOperation.java:65)
        at com.mongodb.Mongo$3.execute(Mongo.java:837)
        at com.mongodb.MongoCollectionImpl.executeBulkWrite(MongoCollectionImpl.java:481)
        at com.mongodb.MongoCollectionImpl.bulkWrite(MongoCollectionImpl.java:413)
        at com.mongodb.MongoCollectionImpl.bulkWrite(MongoCollectionImpl.java:408)
        at com.datamountaineer.streamreactor.connect.mongodb.sink.MongoWriter$$anonfun$insert$2$$anonfun$apply$4.apply(MongoWriter.scala:114)
        at com.datamountaineer.streamreactor.connect.mongodb.sink.MongoWriter$$anonfun$insert$2$$anonfun$apply$4.apply(MongoWriter.scala:113)
        at scala.collection.Iterator$class.foreach(Iterator.scala:891)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
        at com.datamountaineer.streamreactor.connect.mongodb.sink.MongoWriter$$anonfun$insert$2.apply(MongoWriter.scala:113)
```

### What is your Connect cluster configuration (connect-avro-distributed.properties)?
See in attached zip file: connect-distributed.properties

### What is your connector properties configuration (my-connector.properties)?
See in attached zip file: connector-config.json

### Please provide full log files (redact and sensitive information)
See in attached zip file: kafka-connector-log.txt

**Comment by invadergir** [comment]
FYI - I have a PR that fixes this issue, I just need to add some more tests.  I should be ready to push it by end of week.  (My sprint is closing soon so have to set this aside now...)

**Comment by invadergir** [comment]
Update, this will be coming this week most likely.

**Comment by invadergir** [comment]
Sorry, I forgot to close this. This is fixed with the above merge.  Closing now.
