### ISSUE TITLE
Avro field with default value does not create table in Kudu

### ISSUE THREAD

**Issue by rad08d** [Landoop/stream-reactor#475]
Given an Avro schema like the following:

```"{\"type\":\"record\",\"name\":\"thing\",\"doc\":\"description",\"fields\":[{\"name\":\"thing1\",\"type\":\"string\"},{\"name\":\"thing2\",\"type\":\"string\"},{\"name\":\"thing3\",\"type\":\"string\"},{\"name\":\"thing4\",\"type\":\"string\"},{\"name\":\"thing5\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"thing6\",\"type\":[\"double\",\"null\"]},{\"name\":\"thing7\",\"type\":[\"double\",\"null\"]},{\"name\":\"thing8\",\"type\":[\"string\",\"null\"]},{\"name\":\"thing9\",\"type\":\"string\"},{\"name\":\"thing10\",\"type\":[\"string\",\"null\"]},{\"name\":\"thing11\",\"type\":[\"string\",\"null\"]},{\"name\":\"thing12\",\"type\":\"string\"},{\"name\":\"thing13\",\"type\":\"int\"},{\"name\":\"thing14\",\"type\":[\"string\",\"null\"]},{\"name\":\"thing15\",\"type\":[\"int\",\"null\"]}]}"```

the field with a default value, in this case `thing5`, causes an exception while creating a Kudu table.

This results in the following stack trace:
```
INFO Executing create table on impala::platform.kudu_thing with org.apache.kudu.Schema@3a2f3c08 and props org.apache.kudu.client.CreateTableOptions@6722304 (com.datamountaineer.streamreactor.connect.kudu.sink.DbHandler$)
 [2018-06-29 15:54:38,005] WARN Unable to create tables at startup! Tables will be created on delivery of the first record (com.datamountaineer.streamreactor.connect.kudu.sink.KuduWriter)
 org.apache.kudu.client.NonRecoverableException: org.codehaus.jackson.node.NullNode cannot be cast to java.lang.String
 	at org.apache.kudu.client.KuduException.transformException(KuduException.java:132)
 	at org.apache.kudu.client.KuduClient.joinAndHandleException(KuduClient.java:352)
 	at org.apache.kudu.client.KuduClient.createTable(KuduClient.java:96)
 	at com.datamountaineer.streamreactor.connect.kudu.sink.DbHandler$.executeCreateTable(DbHandler.scala:282)
 	at com.datamountaineer.streamreactor.connect.kudu.sink.DbHandler$$anonfun$createTables$2.apply(DbHandler.scala:116)
 	at com.datamountaineer.streamreactor.connect.kudu.sink.DbHandler$$anonfun$createTables$2.apply(DbHandler.scala:116)
 	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
 	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
 	at scala.collection.immutable.Set$Set1.foreach(Set.scala:94)
 	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
 	at scala.collection.AbstractSet.scala$collection$SetLike$$super$map(Set.scala:47)
 	at scala.collection.SetLike$class.map(SetLike.scala:92)
 	at scala.collection.AbstractSet.map(Set.scala:47)
 	at com.datamountaineer.streamreactor.connect.kudu.sink.DbHandler$.createTables(DbHandler.scala:116)
 	at com.datamountaineer.streamreactor.connect.kudu.sink.KuduWriter$$anonfun$3.apply(KuduWriter.scala:53)
 	at com.datamountaineer.streamreactor.connect.kudu.sink.KuduWriter$$anonfun$3.apply(KuduWriter.scala:53)
 	at scala.util.Try$.apply(Try.scala:192)
 	at com.datamountaineer.streamreactor.connect.kudu.sink.KuduWriter.<init>(KuduWriter.scala:53)
 	at com.datamountaineer.streamreactor.connect.kudu.sink.KuduWriter$.apply(KuduWriter.scala:45)
 	at com.datamountaineer.streamreactor.connect.kudu.sink.KuduSinkTask.start(KuduSinkTask.scala:58)
 	at org.apache.kafka.connect.runtime.WorkerSinkTask.initializeAndStart(WorkerSinkTask.java:281)
 	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:170)
 	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:170)
 	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:214)
 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
 	at java.lang.Thread.run(Thread.java:748)
 Caused by: java.lang.ClassCastException: org.codehaus.jackson.node.NullNode cannot be cast to java.lang.String
 	at org.apache.kudu.client.ProtobufHelper.objectToWireFormat(ProtobufHelper.java:235)
 	at org.apache.kudu.client.ProtobufHelper.columnToPb(ProtobufHelper.java:86)
 	at org.apache.kudu.client.ProtobufHelper.schemaToListPb(ProtobufHelper.java:54)
 	at org.apache.kudu.client.ProtobufHelper.schemaToPb(ProtobufHelper.java:62)
 	at org.apache.kudu.client.CreateTableRequest.createRequestPB(CreateTableRequest.java:55)
 	at org.apache.kudu.client.RpcProxy.rpcToMessage(RpcProxy.java:167)
 	at org.apache.kudu.client.RpcProxy.sendRpc(RpcProxy.java:127)
 	at org.apache.kudu.client.AsyncKuduClient.sendRpcToTablet(AsyncKuduClient.java:1024)
 	at org.apache.kudu.client.AsyncKuduClient.createTable(AsyncKuduClient.java:524)
 	at org.apache.kudu.client.KuduClient.createTable(KuduClient.java:95)
 	... 26 more
 [2018-06-29 15:54:38,024] INFO WorkerSinkTask{id=kudu-thing-0} Sink task finished initialization and start (org.apache.kafka.connect.runtime.WorkerSinkTask)
```

I've tracked down where the Jackson null node is being provided instead of just a null value and have a PR ready for the fix.

**Comment by rad08d** [comment]
The patch was merged. Closing issue.
