### ISSUE TITLE
Redis sink. requirement failed: No writers set for connect.redis.kcql! with select * and scoring in sorted set

### ISSUE THREAD

**Issue by Kvitral** [Landoop/stream-reactor#500]
# Issue Guidelines

Please review these questions before submitting any issue?

### What version of the Stream Rector are you reporting this issue for?
stream-reactor-1.1.0

### What is the expected behaviour?
From docs :

> INSERT INTO cpu_stats SELECT * from cpuTopic STOREAS SortedSet(score=timestamp)

My KCQL:

>INSERT INTO myTopic_ss SELECT * from myTopic STOREAS SortedSet(score=dataTs)

I expect that this query will create single sorted set with dataTs field from avro message used as scoring value

### What was observed?
`
java.lang.IllegalArgumentException: requirement failed: No writers set for connect.redis.kcql!
	at scala.Predef$.require(Predef.scala:224)
	at com.datamountaineer.streamreactor.connect.redis.sink.RedisSinkTask.start(RedisSinkTask.scala:100)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.initializeAndStart(WorkerSinkTask.java:301)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:190)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:175)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:219)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
`

### My connector config

connector.class=com.datamountaineer.streamreactor.connect.redis.sink.RedisSinkConnector
connect.redis.port=12345
connect.redis.kcql=INSERT INTO myTopic_ss SELECT * from myTopic STOREAS SortedSet(score=dataTs)
topics=myTopic
tasks.max=1
connect.redis.host=127.0.0.1
connect.redis.password=strong_password

**Comment by andrewstevenson** [comment]
@Kvitral Can you build from master? This was addressed in https://github.com/Landoop/stream-reactor/pull/454. If you add you KCQL to https://github.com/Landoop/stream-reactor/blob/master/kafka-connect-redis/src/test/scala/com/datamountaineer/streamreactor/connect/redis/sink/RedisSinkTaskTest.scala#L31 you can step through the unit test to set it accept the KCQL

**Comment by andrewstevenson** [comment]
@Kvitral I'm closing this. Reopen if it persists.

**Comment by masihyeganeh** [comment]
I have the same error here.
Does the latest release (1.1.0) contain this fix?

**Comment by andrewstevenson** [comment]
@masihyeganeh No, only mater

**Comment by masihyeganeh** [comment]
I just built from master and problem still exists
