### ISSUE TITLE
Kafka-connect-ftp gives exception when connecting to SFTP

### ISSUE THREAD

**Issue by kbpartha24** [Landoop/stream-reactor#505]
Version: Confluent 5.0

What is the expected behavior?
The file should be read and data should be copied to Kafka topic.

What was observed?

[2018-10-16 10:34:45,949] ERROR WorkerSourceTask{id=ftpcheck-0} Task threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask:177)
org.apache.commons.net.MalformedServerReplyException: Could not parse response code.
Server Reply: SSH-2.0-OpenSSH_7.4
       at org.apache.commons.net.ftp.FTP.__getReply(FTP.java:336)
       at org.apache.commons.net.ftp.FTP.__getReply(FTP.java:292)
       at org.apache.commons.net.ftp.FTP._connectAction_(FTP.java:405)
       at org.apache.commons.net.ftp.FTPClient._connectAction_(FTPClient.java:966)
       at org.apache.commons.net.ftp.FTPClient._connectAction_(FTPClient.java:954)
       at org.apache.commons.net.ftp.FTPSClient._connectAction_(FTPSClient.java:222)
       at org.apache.commons.net.SocketClient.connect(SocketClient.java:189)
       at org.apache.commons.net.SocketClient.connect(SocketClient.java:209)
       at com.datamountaineer.streamreactor.connect.ftp.source.FtpMonitor.connectFtp(FtpMonitor.scala:163)
       at com.datamountaineer.streamreactor.connect.ftp.source.FtpMonitor.poll(FtpMonitor.scala:187)
       at com.datamountaineer.streamreactor.connect.ftp.source.FtpSourcePoller.fetchRecords(FtpSourceTask.scala:78)
       at com.datamountaineer.streamreactor.connect.ftp.source.FtpSourcePoller.poll(FtpSourceTask.scala:69)
       at com.datamountaineer.streamreactor.connect.ftp.source.FtpSourceTask.poll(FtpSourceTask.scala:121)
       at org.apache.kafka.connect.runtime.WorkerSourceTask.poll(WorkerSourceTask.java:244)
       at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:220)
       at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:175)
       at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:219)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
       at java.lang.Thread.run(Thread.java:748)
[2018-10-16 10:34:45,952] ERROR WorkerSourceTask{id=ftpcheck-0} Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask:178)

myconfig is 

My config is
{
 "connector.class": "com.datamountaineer.streamreactor.connect.ftp.source.FtpSourceConnector",
 "name": "ftpcheck",
 "connect.ftp.address": "server:22",
 "connect.ftp.user": "ftp",
 "connect.ftp.password": "****",
 "connect.ftp.refresh": "PT1S",
 "connect.ftp.file.maxage": "P14D",
 "connect.ftp.monitor.update": "/ftp/:ftp-data",
 "connect.ftp.keystyle": "struct",
 "connect.ftp.protocol": "SFTP",
 "connect.ftp.filter": "*.xml"
}

I checked FtpMonitor.scala in that when SFTP is defined
class FtpMonitor(settings:FtpMonitorSettings, fileConverter: FileConverter) extends StrictLogging {
 val MaxAge = settings.maxAge.getOrElse(Duration.ofDays(Long.MaxValue))

 val ftp = settings.protocol match {
   case FtpProtocol.FTP => new FTPClient()
   case FtpProtocol.SFTP => new FTPSClient()
 }
I think since FTPSClient is made we get the exception. Since my ftp is SFTP configured.

**Comment by alexmorosmarco** [comment]
Hi, I am also interested in this problem as I want to use the "FTP to Kafka" connector but to connect to an SFTP server.

@kbpartha24 did you have any response by other channel different than GitHub or did you get how to connect to the SFTP server?

Thanks a lot!

**Comment by alexmorosmarco** [comment]
Ok, I kind of have the response for you @kbpartha24 as we have had the same problem.

We were trying to use this connector to connect to an SFTP.
So we also tried to put the protocol to ``SFTP`` and the port to proper one (``22``), as you were doing.

Then I have checked [the code config class](https://github.com/Landoop/stream-reactor/blob/master/kafka-connect-ftp/src/main/scala/com/datamountaineer/streamreactor/connect/ftp/source/FtpSourceConfig.scala).
If you check the description of the param ``"connect.ftp.protocol"`` it says ``"FTPS or FTP protocol"``.
This has made me think that what this connector supports is connecting exactly by FTP protocol or FTPS protocol (so FTP over TLS), but **not SFTP**. (Of course Landoop team, correct me if I am wrong please).

In our case we have a server that allows conneting through SFTP but also through FTPS.
So we have configured the connector to use the port ``21`` (FTP common port) and the protocol ``SFTP``, **and it works**.

**Why does it work if you are configuring ``SFTP`` protocol but "you" have told me that you are connecting through ``FTPS`` over port ``21``?**
* Quick answer: I think it is a defect on the constant name.
* Long answer: I have checked the [history on the config class](https://github.com/Landoop/stream-reactor/commits/master/kafka-connect-ftp/src/main/scala/com/datamountaineer/streamreactor/connect/ftp/source/FtpSourceConfig.scala) and [there is a commit](https://github.com/Landoop/stream-reactor/commit/02a29e7bd853d851fcb6d8709ea777375fa6dc21#diff-4d72d8614ad1ee98c2952377ec1c8671) where the constant ``FTPS`` value was renamed to ``SFTP`` maintaining to use the same ``FTPSClient`` so I think that renaming is actually wrong, I don't understand why it has been renamed.

I am creating an issue to revert that renaming and also one to ask about if there are plans to implement SFTP connection.

**Comment by andrewstevenson** [comment]
@alexmorosmarco @kbpartha24 This indeed was a typo, the sink accepts FTPS or FTP as the protocol and the documentation has been updated and will be released with the [Lenses](https://lenses.io) 3.0 coming soon. Glad to hear it works with SFTP if the FTP server is configured accordingly
