### ISSUE TITLE
Error while attempting to create/find topic(s) 'connect-offsets'

### ISSUE THREAD

**Issue by junaidrazzaq323** [Landoop/stream-reactor#508]
Using **datamountaineer/kafka-connect-cassandra:1.1.0** docker image.

I have the following configs set in connector properties:

```
CONNECT_STATUS_STORAGE_TOPIC = "connect-statuses"
CONNECT_CONFIG_STORAGE_TOPIC = "connect-configs"
CONNECT_OFFSET_STORAGE_TOPIC = "connect-offsets"
CONNECT_STATUS_STORAGE_REPLICATION_FACTOR = 1
CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR = 1
CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR = 1
```

Cassandra was unavailable for some time due to which kafka connect stopped. On Restarting Kafka-Connect I get the below exception:

```
[2018-11-05 07:01:53,391] ERROR Uncaught exception in herder work thread, exiting:  (org.apache.kafka.connect.runtime.distributed.DistributedHerder)
org.apache.kafka.connect.errors.ConnectException: Error while attempting to create/find topic(s) 'connect-offsets'
        at org.apache.kafka.connect.util.TopicAdmin.createTopics(TopicAdmin.java:255)
        at org.apache.kafka.connect.storage.KafkaOffsetBackingStore$1.run(KafkaOffsetBackingStore.java:100)
        at org.apache.kafka.connect.util.KafkaBasedLog.start(KafkaBasedLog.java:126)
        at org.apache.kafka.connect.storage.KafkaOffsetBackingStore.start(KafkaOffsetBackingStore.java:110)
        at org.apache.kafka.connect.runtime.Worker.start(Worker.java:141)
        at org.apache.kafka.connect.runtime.AbstractHerder.startServices(AbstractHerder.java:108)
        at org.apache.kafka.connect.runtime.distributed.DistributedHerder.run(DistributedHerder.java:211)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.NotControllerException: This is not the correct controller for this cluster.
        at org.apache.kafka.common.internals.KafkaFutureImpl.wrapAndThrow(KafkaFutureImpl.java:45)
        at org.apache.kafka.common.internals.KafkaFutureImpl.access$000(KafkaFutureImpl.java:32)
        at org.apache.kafka.common.internals.KafkaFutureImpl$SingleWaiter.await(KafkaFutureImpl.java:89)
        at org.apache.kafka.common.internals.KafkaFutureImpl.get(KafkaFutureImpl.java:258)
        at org.apache.kafka.connect.util.TopicAdmin.createTopics(TopicAdmin.java:228)
        ... 11 more
Caused by: org.apache.kafka.common.errors.NotControllerException: This is not the correct controller for this cluster.
```
I think its something similar to this https://github.com/confluentinc/kafka-connect-jdbc/issues/189 but I am not sure.

**Comment by andrewstevenson** [comment]
@junaidrazzaq323  I think its the same but since its an issue with the framework and not the sink I'm closing it.
