### ISSUE TITLE
Kafka connect cassandra sink- Error for Json Data Insertion

### ISSUE THREAD

**Issue by jaytanwar1** [Landoop/stream-reactor#509]
I am using kafka connect 1.0.0 with kafka version 1.0 for my kafka-cassandra-sink.created a test topic IndiaDataEngineerTest and a cassandra table  indiatest having structure as IndiaTest (datetime timeuuid, city text, phone_number text,PRIMARY KEY (datetime,phone_number)); 
In my topic data is written as json from a producer as below:

    {"datetime":"c8ba2390-4783-11e8-af08-d9271f3c3d48","city":"Santa Monica","phone_number":"+131000000001"}
    {"datetime":"42485b20-44f3-11e8-b543-77b9a2d3bc92","city":"Anaheim","phone_number":"+131000000002"}
    {"datetime":"53b5c980-41c7-11e8-8689-7983010e6437","city":"Not Found","phone_number":"+131000000004"}
    {"datetime":"d43b3860-419a-11e8-a2eb-59f9c7b79f07","city":"Anaheim","phone_number":"+131000000003"}

i am tryig to write above data in my cassandra table using below sink prop as below:
`    {
"name": "cassandra-sink",
"config": {
"tasks.max":"1",
"connector.class":"com.datamountaineer.streamreactor.connect.cassandra.sink.CassandraSinkConnector",
    "topics":"IndiaDataEngineerTest",
    "connect.cassandra.contact.points": "www.abc.com",
    "connect.cassandra.port": 9042,
    "connect.cassandra.username": "jay",
    "connect.cassandra.password": "jaytest",
    "connect.cassandra.key.space": "message",
    "connect.cassandra.kcql":"INSERT INTO IndiaTest SELECT datetime,city,phone_number FROM IndiaDataEngineerTest"
	}
    }`

Now after starting connect as soon I send the config file following error encountered.

[2018-11-14 00:33:52,742] INFO Detected Guava >= 19 in the classpath, using modern compatibility layer (com.datastax.driver.core.GuavaCompatibility:132)
[2018-11-14 00:33:53,031] INFO Using native clock to generate timestamps. (com.datastax.driver.core.ClockFactory:52)
[2018-11-14 00:33:53,167] INFO Found Netty's native epoll transport in the classpath, using it (com.datastax.driver.core.NettyUtil:79)
[2018-11-14 00:33:54,089] INFO Using data-center name 'datacenter1' for DCAwareRoundRobinPolicy (if this is incorrect, please provide the correct datacenter name with DCAwareRoundRobinPolicy constructor) (com.datastax.driver.core.policies.DCAwareRoundRobinPolicy:95)
[2018-11-14 00:33:54,091] INFO New Cassandra host id2374la.ytel.com/172.21.54.3:9042 added (com.datastax.driver.core.Cluster:1568)
[2018-11-14 00:33:54,092] INFO New Cassandra host /172.21.54.5:9042 added (com.datastax.driver.core.Cluster:1568)
[2018-11-14 00:33:54,092] INFO New Cassandra host /172.21.54.6:9042 added (com.datastax.driver.core.Cluster:1568)
[2018-11-14 00:33:54,234] INFO Initialising Cassandra writer. (com.datamountaineer.streamreactor.connect.cassandra.sink.CassandraJsonWriter:48)
[2018-11-14 00:33:54,337] INFO Preparing statements for IndiaDataEngineerTest->indiatest (com.datamountaineer.streamreactor.connect.cassandra.sink.CassandraJsonWriter:83)
[2018-11-14 00:33:54,356] ERROR Encountered error line 1:33 missing '(' at '<missing ' (com.datamountaineer.streamreactor.connect.cassandra.sink.CassandraJsonWriter:62)
com.datastax.driver.core.exceptions.SyntaxError: line 1:33 missing '(' at '<missing '
	at com.datastax.driver.core.exceptions.SyntaxError.copy(SyntaxError.java:58)
	at com.datastax.driver.core.exceptions.SyntaxError.copy(SyntaxError.java:24)
	at com.datastax.driver.core.DriverThrowables.propagateCause(DriverThrowables.java:37)
	at com.datastax.driver.core.AbstractSession.prepare(AbstractSession.java:104)
	at com.datamountaineer.streamreactor.connect.cassandra.sink.CassandraJsonWriter$$anonfun$3.apply(CassandraJsonWriter.scala:108)
	at com.datamountaineer.streamreactor.connect.cassandra.sink.CassandraJsonWriter$$anonfun$3.apply(CassandraJsonWriter.scala:104)
	at scala.util.Try$.apply(Try.scala:192)
	at com.datamountaineer.streamreactor.connect.cassandra.sink.CassandraJsonWriter.com$datamountaineer$streamreactor$connect$cassandra$sink$CassandraJsonWriter$$getPreparedStatement(CassandraJsonWriter.scala:104)
	at com.datamountaineer.streamreactor.connect.cassandra.sink.CassandraJsonWriter$$anonfun$cachePreparedStatements$2$$anonfun$2.apply(CassandraJsonWriter.scala:84)
	at com.datamountaineer.streamreactor.connect.cassandra.sink.CassandraJsonWriter$$anonfun$cachePreparedStatements$2$$anonfun$2.apply(CassandraJsonWriter.scala:80)
	at scala.collection.IndexedSeqOptimized$class.foldl(IndexedSeqOptimized.scala:57)
	at scala.collection.IndexedSeqOptimized$class.foldLeft(IndexedSeqOptimized.scala:66)
	at scala.collection.mutable.ArrayBuffer.foldLeft(ArrayBuffer.scala:48)
	at com.datamountaineer.streamreactor.connect.cassandra.sink.CassandraJsonWriter$$anonfun$cachePreparedStatements$2.apply(CassandraJsonWriter.scala:80)
	at com.datamountaineer.streamreactor.connect.cassandra.sink.CassandraJsonWriter$$anonfun$cachePreparedStatements$2.apply(CassandraJsonWriter.scala:79)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.immutable.Map$Map1.foreach(Map.scala:116)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at com.datamountaineer.streamreactor.connect.cassandra.sink.CassandraJsonWriter.cachePreparedStatements(CassandraJsonWriter.scala:79)
	at com.datamountaineer.streamreactor.connect.cassandra.sink.CassandraJsonWriter.<init>(CassandraJsonWriter.scala:56)
	at com.datamountaineer.streamreactor.connect.cassandra.sink.CassandraWriter$.apply(CassandraWriter.scala:43)
	at com.datamountaineer.streamreactor.connect.cassandra.sink.CassandraSinkTask.start(CassandraSinkTask.scala:60)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.initializeAndStart(WorkerSinkTask.java:207)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:139)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:140)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:175)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.datastax.driver.core.exceptions.SyntaxError: line 1:33 missing '(' at '<missing '
	at com.datastax.driver.core.Responses$Error.asException(Responses.java:144)
	at com.datastax.driver.core.SessionManager$4.apply(SessionManager.java:220)
	at com.datastax.driver.core.SessionManager$4.apply(SessionManager.java:196)
	at com.google.common.util.concurrent.Futures$AsyncChainingFuture.doTransform(Futures.java:1442)
	at com.google.common.util.concurrent.Futures$AsyncChainingFuture.doTransform(Futures.java:1433)
	at com.google.common.util.concurrent.Futures$AbstractChainingFuture.run(Futures.java:1408)
	at com.google.common.util.concurrent.Futures$2$1.run(Futures.java:1177)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
	... 1 more
[2018-11-14 00:33:54,360] ERROR Task cassandra-sink-connect-0 threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask:142)
java.lang.RuntimeException: com.datastax.driver.core.exceptions.SyntaxError: line 1:33 missing '(' at '<missing '
	at com.datamountaineer.streamreactor.connect.errors.ThrowErrorPolicy.handle(ErrorPolicy.scala:58)
	at com.datamountaineer.streamreactor.connect.errors.ErrorHandler$class.handleError(ErrorHandler.scala:83)
	at com.datamountaineer.streamreactor.connect.errors.ErrorHandler$class.handleTry(ErrorHandler.scala:64)
	at com.datamountaineer.streamreactor.connect.cassandra.sink.CassandraJsonWriter.handleTry(CassandraJsonWriter.scala:45)
	at com.datamountaineer.streamreactor.connect.cassandra.sink.CassandraJsonWriter.com$datamountaineer$streamreactor$connect$cassandra$sink$CassandraJsonWriter$$getPreparedStatement(CassandraJsonWriter.scala:113)
	at com.datamountaineer.streamreactor.connect.cassandra.sink.CassandraJsonWriter$$anonfun$cachePreparedStatements$2$$anonfun$2.apply(CassandraJsonWriter.scala:84)
	at com.datamountaineer.streamreactor.connect.cassandra.sink.CassandraJsonWriter$$anonfun$cachePreparedStatements$2$$anonfun$2.apply(CassandraJsonWriter.scala:80)
	at scala.collection.IndexedSeqOptimized$class.foldl(IndexedSeqOptimized.scala:57)
	at scala.collection.IndexedSeqOptimized$class.foldLeft(IndexedSeqOptimized.scala:66)
	at scala.collection.mutable.ArrayBuffer.foldLeft(ArrayBuffer.scala:48)
	at com.datamountaineer.streamreactor.connect.cassandra.sink.CassandraJsonWriter$$anonfun$cachePreparedStatements$2.apply(CassandraJsonWriter.scala:80)
	at com.datamountaineer.streamreactor.connect.cassandra.sink.CassandraJsonWriter$$anonfun$cachePreparedStatements$2.apply(CassandraJsonWriter.scala:79)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.immutable.Map$Map1.foreach(Map.scala:116)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at com.datamountaineer.streamreactor.connect.cassandra.sink.CassandraJsonWriter.cachePreparedStatements(CassandraJsonWriter.scala:79)
	at com.datamountaineer.streamreactor.connect.cassandra.sink.CassandraJsonWriter.<init>(CassandraJsonWriter.scala:56)
	at com.datamountaineer.streamreactor.connect.cassandra.sink.CassandraWriter$.apply(CassandraWriter.scala:43)
	at com.datamountaineer.streamreactor.connect.cassandra.sink.CassandraSinkTask.start(CassandraSinkTask.scala:60)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.initializeAndStart(WorkerSinkTask.java:207)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:139)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:140)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:175)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.datastax.driver.core.exceptions.SyntaxError: line 1:33 missing '(' at '<missing '
	at com.datastax.driver.core.exceptions.SyntaxError.copy(SyntaxError.java:58)
	at com.datastax.driver.core.exceptions.SyntaxError.copy(SyntaxError.java:24)
	at com.datastax.driver.core.DriverThrowables.propagateCause(DriverThrowables.java:37)
	at com.datastax.driver.core.AbstractSession.prepare(AbstractSession.java:104)
	at com.datamountaineer.streamreactor.connect.cassandra.sink.CassandraJsonWriter$$anonfun$3.apply(CassandraJsonWriter.scala:108)
	at com.datamountaineer.streamreactor.connect.cassandra.sink.CassandraJsonWriter$$anonfun$3.apply(CassandraJsonWriter.scala:104)
	at scala.util.Try$.apply(Try.scala:192)
	at com.datamountaineer.streamreactor.connect.cassandra.sink.CassandraJsonWriter.com$datamountaineer$streamreactor$connect$cassandra$sink$CassandraJsonWriter$$getPreparedStatement(CassandraJsonWriter.scala:104)
	... 25 more
Caused by: com.datastax.driver.core.exceptions.SyntaxError: line 1:33 missing '(' at '<missing '
	at com.datastax.driver.core.Responses$Error.asException(Responses.java:144)
	at com.datastax.driver.core.SessionManager$4.apply(SessionManager.java:220)
	at com.datastax.driver.core.SessionManager$4.apply(SessionManager.java:196)
	at com.google.common.util.concurrent.Futures$AsyncChainingFuture.doTransform(Futures.java:1442)
	at com.google.common.util.concurrent.Futures$AsyncChainingFuture.doTransform(Futures.java:1433)
	at com.google.common.util.concurrent.Futures$AbstractChainingFuture.run(Futures.java:1408)
	at com.google.common.util.concurrent.Futures$2$1.run(Futures.java:1177)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
	... 1 more
[2018-11-14 00:33:54,362] ERROR Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask:143)
[2018-11-14 00:33:54,362] INFO Stopping Cassandra sink. (com.datamountaineer.streamreactor.connect.cassandra.sink.CassandraSinkTask:79)

Please help me out or suggest what went wrong...??
Advance thanks.

**Comment by andrewstevenson** [comment]
@jaytanwar1 What version of the Stream reactor and what version of Cassandra are you using?

**Comment by andrewstevenson** [comment]
@jaytanwar1 You example works fine in the unit tests for creating the cassandra prepared statement

**Comment by jaytanwar1** [comment]
@andrewstevenson Do I need to add any other config prop to work as it is working in unit tests..?

**Comment by jaytanwar1** [comment]
Thanks.
