### ISSUE TITLE
creating kudu table multi times

### ISSUE THREAD

**Issue by libenchao** [Landoop/stream-reactor#511]
Our config is:
```
{
 "name":"connect_task_name",
 "config":
  {
    "connector.class":"com.datamountaineer.streamreactor.connect.kudu.sink.KuduSinkConnector",
    "tasks.max":1,
    "topics":"topic_name",
    "connect.kudu.master":"kudu-master:7051",
    "connect.kudu.kcql":"UPSERT INTO table_name SELECT * FROM topic_name AUTOCREATE DISTRIBUTEBY id INTO 8 BUCKETS",
    "connect.kudu.write.flush.mode":"SYNC",
    "connect.kudu.mutation.buffer.space":10000,
    "connect.kudu.schema.registry.url":"http://schema-registry-host"
  }
}
```

And if table not exist for the first time, following logs show that kudu tries creating table for multi times.

```
[2018-11-13 20:05:59,349] INFO Executing create table on kudu_table_name with org.apache.kudu.Schema@3a27205c and props org.apache.kudu.client.CreateTableOptions@24dc32e9 (com.datamountaineer.streamreactor.connect.kudu.sink.DbHandler$:332)
[2018-11-13 20:05:59,835] INFO Table kudu_table_name created. (com.datamountaineer.streamreactor.connect.kudu.sink.DbHandler$:334)
[2018-11-13 20:05:59,835] INFO Executing create table on kudu_table_name with org.apache.kudu.Schema@471e11f and props org.apache.kudu.client.CreateTableOptions@6add2072 (com.datamountaineer.streamreactor.connect.kudu.sink.DbHandler$:332)
[2018-11-13 20:05:59,843] WARN Unable to create tables at startup! Tables will be created on delivery of the first record (com.datamountaineer.streamreactor.connect.kudu.sink.KuduWriter:56)
org.apache.kudu.client.NonRecoverableException: Table kudu_table_name already exists with id 53a2201d9d05459b93a0ae85d3fd60e8
        at org.apache.kudu.client.KuduException.transformException(KuduException.java:110)
        at org.apache.kudu.client.KuduClient.joinAndHandleException(KuduClient.java:352)
        at org.apache.kudu.client.KuduClient.createTable(KuduClient.java:96)
        at com.datamountaineer.streamreactor.connect.kudu.sink.DbHandler$.executeCreateTable(DbHandler.scala:333)
        at com.datamountaineer.streamreactor.connect.kudu.sink.DbHandler$$anonfun$createTables$2.apply(DbHandler.scala:117)
        at com.datamountaineer.streamreactor.connect.kudu.sink.DbHandler$$anonfun$createTables$2.apply(DbHandler.scala:117)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.immutable.HashSet$HashSet1.foreach(HashSet.scala:316)
        at scala.collection.immutable.HashSet$HashTrieSet.foreach(HashSet.scala:972)
        at scala.collection.immutable.HashSet$HashTrieSet.foreach(HashSet.scala:972)
        at scala.collection.immutable.HashSet$HashTrieSet.foreach(HashSet.scala:972)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
        at scala.collection.AbstractSet.scala$collection$SetLike$$super$map(Set.scala:47)
        at scala.collection.SetLike$class.map(SetLike.scala:92)
        at scala.collection.AbstractSet.map(Set.scala:47)
        at com.datamountaineer.streamreactor.connect.kudu.sink.DbHandler$.createTables(DbHandler.scala:117)
        at com.datamountaineer.streamreactor.connect.kudu.sink.KuduWriter$$anonfun$3.apply(KuduWriter.scala:54)
        at com.datamountaineer.streamreactor.connect.kudu.sink.KuduWriter$$anonfun$3.apply(KuduWriter.scala:54)
        at scala.util.Try$.apply(Try.scala:192)
        at com.datamountaineer.streamreactor.connect.kudu.sink.KuduWriter.<init>(KuduWriter.scala:54)
        at com.datamountaineer.streamreactor.connect.kudu.sink.KuduWriter$.apply(KuduWriter.scala:46)
        at com.datamountaineer.streamreactor.connect.kudu.sink.KuduSinkTask.start(KuduSinkTask.scala:58)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.initializeAndStart(WorkerSinkTask.java:281)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:170)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:170)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:214)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

And I have a pr (https://github.com/Landoop/stream-reactor/pull/510) for this bug.

**Comment by andrewstevenson** [comment]
@libenchao I've merged your PR. Can you confirm it works then close this issue?

**Comment by libenchao** [comment]
@andrewstevenson Thanks, it does work. I will close this issue.
