### ISSUE TITLE
 Casandra source Mapping tinyint to short(should be byte) 

### ISSUE THREAD

**Issue by ankitsingh250** [Landoop/stream-reactor#571]
I am using  source connector to  push my data from cassandra   table to kafka topic but for the the column of data type tinyint it is try to convert it into short and i am getting excetption 

=> org.apache.kafka.connect.errors.ConnectException: Connector msg-connector error processing row Row[6181, 12084, 5341, NULL, NULL, NULL, {"cardType":"BASIC_CARD","cardId":null,"msgText":"uuqieybqibdi2w","msgContentType":"TEXT","msgAttachmentUrl":null,"caption":null}, 0, NULL, 0, Tue Apr 09 16:06:50 IST 2019, NULL, 1232433602057, NULL, 0, false, NULL, 3, NULL, 7, NULL, NULL, NULL, NULL, 1, 3, Tue Apr 09 16:06:50 IST 2019] for table chat_inbox.chat_message.
at com.datamountaineer.streamreactor.connect.cassandra.source.CassandraTableReader$$anonfun$process$1.applyOrElse(CassandraTableReader.scala:247)
at com.datamountaineer.streamreactor.connect.cassandra.source.CassandraTableReader$$anonfun$process$1.applyOrElse(CassandraTableReader.scala:215)
at scala.concurrent.Future$$anonfun$onSuccess$1.apply(Future.scala:119)
at scala.concurrent.Future$$anonfun$onSuccess$1.apply(Future.scala:117)
at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:36)
at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: com.datastax.driver.core.exceptions.CodecNotFoundException: Codec not found for requested operation: [tinyint <-> java.lang.Short]

I checked yoursouce code and found this  line -> 
case DataType.Name.TINYINT | DataType.Name.SMALLINT => row.getShort(columnDef.getName)

expected => tinyint should be mapped to byte and small int to short

**Comment by andrewstevenson** [comment]
@ankitsingh250 Fancy contributing a PR?
