### ISSUE TITLE
Can't use key from struct in RedisSink Multiple SortedSet

### ISSUE THREAD

**Issue by wowo** [Landoop/stream-reactor#573]
# Issue Guidelines

Please review these questions before submitting any issue?

### What version of the Stream Rector are you reporting this issue for?
1.2.1

### What is the expected behaviour?
I have avro schema
```
{
  "type": "record",
  "name": "Envelope",
  "namespace": "ticket",
  "fields": [
    {
      "name": "before",
      "type": [
        "null",
        {
          "type": "record",
          "name": "Value",
          "fields": [
            {
              "name": "id_ticket",
              "type": "long"
            },
            {
              "name": "id_client",
              "type": [
                "null",
                "int"
              ],
              "default": null
            }
          ],
          "connect.name": "ticket.Value"
        }
      ],
      "default": null
    },
    {
      "name": "after",
      "type": [
        "null",
        "Value"
      ],
      "default": null
    },
    {
      "name": "source",
      "type": {
        "type": "record",
        "name": "Source",
        "namespace": "io.debezium.connector.postgresql",
        "fields": [...],
        "connect.name": "io.debezium.connector.postgresql.Source"
      }
    },
    {
      "name": "op",
      "type": "string"
    },
    {
      "name": "ts_ms",
      "type": [
        "null",
        "long"
      ],
      "default": null
    }
  ],
  "connect.name": "ticket.Envelope"
}
```

Using this KCQL:
```
INSERT INTO test-client-ticket- SELECT after FROM ticket PK after.id_client STOREAS SortedSet(score=ts_ms)
```
I expect to see in Redis:
test-client-ticket-123: list of his tickets (**after** part)

### What was observed?
```
java.util.NoSuchElementException: key not found: id_client
at scala.collection.MapLike$class.default(MapLike.scala:228)
at scala.collection.AbstractMap.default(Map.scala:59)
at scala.collection.MapLike$class.apply(MapLike.scala:141)
at scala.collection.AbstractMap.apply(Map.scala:59)
at com.datamountaineer.streamreactor.connect.redis.sink.writer.RedisMultipleSortedSets$$anonfun$insert$1$$anonfun$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$4$$anonfun$6.apply(RedisMultipleSortedSets.scala:73)
at com.datamountaineer.streamreactor.connect.redis.sink.writer.RedisMultipleSortedSets$$anonfun$insert$1$$anonfun$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$4$$anonfun$6.apply(RedisMultipleSortedSets.scala:73)
at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234
```

Looks like here https://github.com/Landoop/stream-reactor/blob/863ccec50f10f16ab93f74e1f93a2dbc71a816fe/kafka-connect-redis/src/main/scala/com/datamountaineer/streamreactor/connect/redis/sink/writer/RedisMultipleSortedSets.scala#L73 it doesn't see after.id_client (or id_client which I tried too). It only works with top-level keys. 
Two lines above it extracts fields, but only limits it to PK, maybe extracting all fields would help somehow?

### What is your connector properties configuration (my-connector.properties)?
I'm running that connector on distributed kafka-connect:
```
{
  "connector.class": "com.datamountaineer.streamreactor.connect.redis.sink.RedisSinkConnector",
  "connect.redis.port": "6379",
  "connect.redis.kcql": "INSERT INTO test-client-ticket- SELECT after FROM ticket PK after.id_client STOREAS SortedSet(score=ts_ms)",
  "topics": "ticket",
  "tasks.max": "1",
  "connect.redis.host": "***",
  "name": "test_redis_clients_tickets"
}
```

**Comment by stheppi** [comment]
Hello. Yes. Addressing the key(or key fields if it is complex structure) is not supported.

You can use Kafka Single Message Transform to add the key or key fields in the value part.

**Comment by wowo** [comment]
@stheppi pity. Maybe it's worth mentioning it in docs?

**Comment by wowo** [comment]
That actually did a trick:

```
"transforms": "ExtractAfter",
"transforms.ExtractAfter.type": "org.apache.kafka.connect.transforms.ExtractField$Value",
"transforms.ExtractAfter.field": "after",
```

I've lost ts_ms, which was on the same level as after, but can live with that.
