### ISSUE TITLE
Hive sink: Exiting WorkerSinkTask due to unrecoverable exception

### ISSUE THREAD

**Issue by ChethanUK** [Landoop/stream-reactor#583]
# Issue Guidelines

Please review these questions before submitting any issue?

### Do you have a supported version of the data source/sink .i.e Cassandra 3.0.9?
HIVE

### Have you read the [docs](https://docs.lenses.io/connectors/)?
Yes

### What is your Connect cluster configuration (connect-avro-distributed.properties)?
Json No Schema

### What is your connector properties configuration (my-connector.properties)?

```
connector.class=com.landoop.streamreactor.connect.hive.sink.HiveSinkConnector
connect.hive.database.name=ordersconnect
connect.hive.hive.metastore.uris=thrift://Master IP:9083
topics=mytopic
connect.hive.fs.defaultFS=hdfs://Master IP:8020
key.converter.schemas.enable=false
name=orderscolmongot02hive
value.converter.schemas.enable=false
connect.hive.kcql=insert into mytable select * from mytopic AUTOCREATE PARTITION_BY state WITH_FLUSH_INTERVAL = 10
value.converter=org.apache.kafka.connect.json.JsonConverter
key.converter=org.apache.kafka.connect.json.JsonConverter
connect.hive.hive.metastore=thrift
```

### Please provide full log files (redact and sensitive information)
Error:
```
org.apache.kafka.connect.errors.ConnectException: Exiting WorkerSinkTask due to unrecoverable exception.
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:586)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:322)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:225)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:193)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:175)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:219)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: NoSuchObjectException(message:ordersconnect)
	at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$get_database_result$get_database_resultStandardScheme.read(ThriftHiveMetastore.java:26857)
	at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$get_database_result$get_database_resultStandardScheme.read(ThriftHiveMetastore.java:26834)
	at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$get_database_result.read(ThriftHiveMetastore.java:26765)
	at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:86)
	at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$Client.recv_get_database(ThriftHiveMetastore.java:762)
	at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$Client.get_database(ThriftHiveMetastore.java:749)
	at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.getDatabase(HiveMetaStoreClient.java:1280)
	at com.landoop.streamreactor.connect.hive.package$.createTable(package.scala:113)
	at com.landoop.streamreactor.connect.hive.sink.HiveSink.create$1(HiveSink.scala:58)
	at com.landoop.streamreactor.connect.hive.sink.HiveSink.getOrCreateTable$1(HiveSink.scala:67)
	at com.landoop.streamreactor.connect.hive.sink.HiveSink.init(HiveSink.scala:72)
	at com.landoop.streamreactor.connect.hive.sink.HiveSink.write(HiveSink.scala:110)
	at com.landoop.streamreactor.connect.hive.sink.HiveSinkTask$$anonfun$put$1.apply(HiveSinkTask.scala:68)
	at com.landoop.streamreactor.connect.hive.sink.HiveSinkTask$$anonfun$put$1.apply(HiveSinkTask.scala:60)
	at scala.collection.Iterator$class.foreach(Iterator.scala:891)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at com.landoop.streamreactor.connect.hive.sink.HiveSinkTask.put(HiveSinkTask.scala:60)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:564)
	... 10 more
```

**Comment by stheppi** [comment]
The error says the HIVE metastore does not have a database named `ordersconnect`

**Comment by ChethanUK** [comment]
Okay, Even When I try with other databases, I get following error: 

```
org.apache.kafka.connect.errors.ConnectException: Exiting WorkerSinkTask due to unrecoverable exception.
    at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:586)
    at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:322)
    at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:225)
    at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:193)
    at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:175)
    at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:219)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
**Caused by: java.lang.IllegalArgumentException: Wrong FS: hdfs://testcluster-m/user/hive/warehouse/hive_connect.db/ordersconnects/.streamreactor_orderscolmongot02_0, expected: hdfs://IP:8020**
```

**Comment by stheppi** [comment]
`Wrong FS: hdfs://testcluster-m/user/hive/warehouse/hive_connect.db/ordersconnects/.streamreactor_orderscolmongot02_0, expected: hdfs://IP:8020`

Where is the `testcluster-m`  coming from? `testcluster-m` does not exist in the Sink source code.

`connect.hive.fs.defaultFS=hdfs://Master IP:8020` did you set `Master IP` to be `testcluster-m`?

**Comment by ChethanUK** [comment]
Yes, I set the External IP of Master Node..

**Comment by davidsloan** [comment]
Closing due to deprecation of the hive connector.
