### ISSUE TITLE
Hive Sink: java.lang.NoClassDefFoundError 

### ISSUE THREAD

**Issue by ulfox** [Landoop/stream-reactor#628]
### What version of the Stream Reactor are you reporting this issue for?
1.2.2

### What is the expected behaviour?
Sink to work

### What was observed?
Connect Task always returns this exception:` Could not initialize class com.landoop.streamreactor.connect.hive.ConfigurationBuilder`

### What is your Connect cluster configuration (connect-avro-distributed.properties)?
`key.converter.schema.registry.url=http://localhost:8081
value.converter.schema.registry.url=http://localhost:8081
config.storage.replication.factor=1
offset.storage.topic=connect-offsets
offset.storage.replication.factor=1
key.converter=io.confluent.connect.avro.AvroConverter
config.storage.topic=connect-configs
group.id=connect-fast-data
port=8083
value.converter=io.confluent.connect.avro.AvroConverter
rest.port=8083
status.storage.replication.factor=1
status.storage.topic=connect-statuses
access.control.allow.origin=*
access.control.allow.methods=GET,POST,PUT,DELETE,OPTIONS
jmx.port=9584
plugin.path=/var/run/connect/connectors/stream-reactor,/var/run/connect/connectors/third-party,/connectors
bootstrap.servers=PLAINTEXT://localhost:9092
`
### What is your connector properties configuration (my-connector.properties)?
`connector.class=com.landoop.streamreactor.connect.hive.sink.HiveSinkConnector
connect.hive.database.name=hive_connect
connect.hive.hive.metastore.uris=thrift://hive-metastore:9083
value.converter.schema.registry.url=http://localhost:8081
topics=telecom_italia_data
name=test-hive-sink-4
connect.hive.fs.defaultFS=hdfs://namenode:8020
connect.hive.kcql=INSERT INTO dev_test SELECT SquareId FROM telecom_italia_data AUTOCREATE WITH_FLUSH_INTERVAL = 1
value.converter=io.confluent.connect.avro.AvroConverter
connect.hive.hive.metastore=thrift
key.converter=io.confluent.connect.avro.AvroConverter
key.converter.schema.registry.url=http://localhost:8081
`
### Please provide full log files (redact and sensitive information)
`
java.lang.NoClassDefFoundError: Could not initialize class com.landoop.streamreactor.connect.hive.ConfigurationBuilder$
    at com.landoop.streamreactor.connect.hive.sink.HiveSinkTask.start(HiveSinkTask.scala:52)
    at org.apache.kafka.connect.runtime.WorkerSinkTask.initializeAndStart(WorkerSinkTask.java:301)
    at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:190)
    at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:175)
    at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:219)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)`

**Comment by ulfox** [comment]
This is fixed. The connector is working if you build new jar from master or 1.2.2
